### ISSUE TITLE
Strings missing on Crowding

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#105]
Strings related with Album cover feature are missing on Crowding.

Last thing about writing you should avoid periods and use exclamation points only for appropriate texts like recommended by Google specs.

Source: [Writing - Capitalization & punctuation](https://www.google.com/design/spec/style/writing.html#writing-capitalization-punctuation)

**Comment by dnldsht** [comment]
In the last version the album cover where removed. 
I read the guide lines and strings will be improved

**Comment by ghost** [comment]
Got it, thanks.
