### ISSUE TITLE
EXIF details of pictures

### ISSUE THREAD

**Issue by 51114u9** [UnevenSoftware/LeafPic#106]
I would like have some exif details when is available on images. After resolution include:
- model of device, e.g. "Model: SM-J500M" -> "Camera: SM-J500M"
- f-number/focal length/exposure time/iso values, e.g. "EXIF: f/1.9 3.7mm 1/105s 1600"
- location values, e.g. "Lat: 17, 21, 10.8366 North/South + Lon: 66, 12, 52.0916 East/West" -> "Location: -17.3530102, -66.2144699"

**Comment by g1lg1l** [comment]
I will fix it soon! Stay tuned!:)

**Comment by g1lg1l** [comment]
Fixxed with this [commit](https://github.com/HoraApps/LeafPic/commit/3b3d8fd7721cec027cff0b2a6b2b6950ad4944d9) !;)

**Comment by 51114u9** [comment]
wow! thanks.

I reviewed your source code and found something strange in this [line 586](https://github.com/HoraApps/LeafPic/commit/3b3d8fd7721cec027cff0b2a6b2b6950ad4944d9#diff-9b8f40dca6f30e16088c245d8fb8730eR566) of your commit. it must be `exif.getAttribute(ExifInterface.TAG_GPS_LONGITUDE)`

**Comment by g1lg1l** [comment]
Sorry for that distraction, fixxed [here](https://github.com/HoraApps/LeafPic/commit/692b4bafafe75652b0ee8989c6a6c421226e2beb)!;)
