### ISSUE TITLE
Ascending or descending date sorting not working

### ISSUE THREAD

**Issue by mr-gosh** [UnevenSoftware/LeafPic#114]
In my main foto folder there isn't anything changing when a select or deselect the ascending button with date selected.
When i activate sorting by name and go back to sorting by date - it works...

I am using the f-droid version 0.2.5

**Comment by dnldsht** [comment]
fixed [here](https://github.com/HoraApps/LeafPic/commit/635f6bc98721a558087f31ce4611172b3ecacd5e)!
