### ISSUE TITLE
Missing Camera Button

### ISSUE THREAD

**Issue by BedHead911** [UnevenSoftware/LeafPic#116]
The button to open my camera app seems to be missing.

**Comment by g1lg1l** [comment]
There is a fab that links to camera app, But it's invisibile currently, because we need to Fix it. Stay tuned!:)

**Comment by g1lg1l** [comment]
Hey, i fixxed it in this [commit](https://github.com/HoraApps/LeafPic/commit/0c574225b74a7b5616576a1dbb643debd25678bb)!;)

**Comment by BedHead911** [comment]
Nice. Thanks a lot. Looking forward to the update on f-droid.

**Comment by g1lg1l** [comment]
You are welcome!;)
