### ISSUE TITLE
Error displaying when pictures have exif rotation

### ISSUE THREAD

**Issue by 51114u9** [UnevenSoftware/LeafPic#118]
I have pictures with rotation in exif values. I have screenshots...
- When I open the folder, the thumbnail of picture is displayed correctly https://www.dropbox.com/s/psc5rbd3spg577o/17409.png?dl=0
- When I open picture, the picture is displayed rotated (may be are not read exif rotation) https://www.dropbox.com/s/s53kgili1oxjdvz/17410.png?dl=0
- But, When I view details or edit picture, the picture is displayed correctly https://www.dropbox.com/s/d3snw6zqjewaqp8/17411.png?dl=0

Android 5.1.1, LeafPic v0.2.5 downloaded from FDroid.

**Comment by 51114u9** [comment]
Still with problems. Now, only show correctly the thumbnail of folders. When I open folder and open the image is rotated, but when I edit is correct. `LeafPic 0.3.1`

**Comment by dnldsht** [comment]
Working now on this issue will be fixed soon
Cheers 🍻

**Comment by Almtesh** [comment]
That's curious, because when you browse the folder, picture are the good orientation on thumbnails, but when you open them, there are wrong.

**Comment by p2635** [comment]
I'm having this problem too, hope it's fixed soon.

**Comment by maddler** [comment]
Just confirm this is still a bug on 0.4.

thanks for the great work!

**Comment by Bugsbane** [comment]
Getting this issue on 0.6 beta 1 from fdroid.
