### ISSUE TITLE
Excluding folders asks if you want to delete.

### ISSUE THREAD

**Issue by BedHead911** [UnevenSoftware/LeafPic#119]
I was a bit confused with the "Delete" in the top bar and the text that asks if I wanted to delete when I was just trying to exclude the folder.

**Comment by g1lg1l** [comment]
The message is wrong! I will fix it later! stay tuned!:)

**Comment by g1lg1l** [comment]
fixxed with this [commit](https://github.com/HoraApps/LeafPic/commit/858f6d6d70282361be1ea5e8ac02808d646a9ed4)! stay tuned!;)
