### ISSUE TITLE
Picture Orientation while viewing single photo

### ISSUE THREAD

**Issue by BedHead911** [UnevenSoftware/LeafPic#120]
When viewing a photo, if you go to more -> settings and check picture orientation, the picture will rotate according to your phones orientation. When you uncheck it, the picture will still rotate rather than returning to portrait orientation. It requires exiting the "view single picture mode" to viewing the full album in order for this change to take effect. This can be quite annoying when you have a large album because you lose your place.

**Comment by g1lg1l** [comment]
fixxed with this [commit](https://github.com/HoraApps/LeafPic/commit/858f6d6d70282361be1ea5e8ac02808d646a9ed4). stay tuned!;)
