### ISSUE TITLE
Large folders won't load images

### ISSUE THREAD

**Issue by JunCTionS** [UnevenSoftware/LeafPic#121]
I have a couple of folders with 5000+ images (default camera and whatsapp images folders) and when opening them clicking on the images or videos have no effect.

Tested it with a folder of 1100 images and it does work so the limit is somewhere in between.

I'm using the F-droid 0.25 LeafPic version on a SGS5. Quickpic and default gallery have no issue with the folders.

**Comment by revuwa** [comment]
I've tested round about 10 folders with pictures and videos in it. Some folders have <10 media files, and one folder have ~1400 pictures. None of them got a preview (thumbnail) on the first LeafPic start. But after waiting several minutes(!) leaving the app opened, some thumbnails came in slowly. 

Finally, a few days later, I still doesn't see all the thumbnails, but some:
- round about 30% of the big picture folder,
- round about 100% of any other picture folder with <10 pictures, and
- round about 50% of other folders, filled with 20 - 80 *.mp4 files.

It would be cool, if this could be fixed could get a speedup in any way.

I'm using the v0.2.7, from the F-Droid repo on my Samsung i9300 @ AOSP 6.0.1.

Thanks in advance for looking into this.

**Comment by ImAnnoying** [comment]
For me pictures load and GIFs move, but when I try to open something it just crashes...
Samsung I9301i 5.1.1
Otherwise the gallery and video player are great!

**Comment by g1lg1l** [comment]
Hey guys, fixxed here: [release 0.3.1](https://github.com/HoraApps/LeafPic/releases/tag/v0.3.1) , stay tuned!;)
