### ISSUE TITLE
Feature request: Link to home screen

### ISSUE THREAD

**Issue by JunCTionS** [UnevenSoftware/LeafPic#122]
I'd love to be able to make links to specific folders in the home screen for quick access of certain content.

**Comment by dnldsht** [comment]
there is a feature like this: you have to select albums an then in the menu there is a option called "Install shortcut" now it just show the app icon but later i will add the album cover.

**Comment by JunCTionS** [comment]
Ah cool, although it must be in a more recent commit, right now when I select album(s) I only get: Exclude, Hide, Rename, Select All, Settings in the menu.
(again, using v0.25 from F-droid)

**Comment by g1lg1l** [comment]
cover album image on album shortcut fixxed with this [commit](https://github.com/HoraApps/LeafPic/commit/858f6d6d70282361be1ea5e8ac02808d646a9ed4)! stay tuned!:)
