### ISSUE TITLE
Repeatable - Trying to view image details: Unfortunately, LeafaPic has stopped

### ISSUE THREAD

**Issue by Rbagman** [UnevenSoftware/LeafPic#123]
I get this error when I try to view image details.

Samsung Note 2 GT-N7100/Android 4.4.2, rooted.

**Comment by g1lg1l** [comment]
The kit Kat version of leaf is very bugghy and instable at the moment, we will support kit Kat well but later we need more time! Sorry, stay tuned, we will do our best as soon as we can!

**Comment by Rbagman** [comment]
No problem, the editor is the key feature for me. Honestly, Android's default app can't rotate images. 

I converted Leaf' to a system app, I will let you know if anything comes up.

**Comment by g1lg1l** [comment]
fixxed in this [release](https://github.com/HoraApps/LeafPic/releases/tag/v0.3.1), stay tuned!;)
