### ISSUE TITLE
Black Theme for AMOLED display

### ISSUE THREAD

**Issue by BedHead911** [UnevenSoftware/LeafPic#127]
Currently, dark mode results in gray color menu and background. It would be great if we could have a pitch black mode #000000 because it can save battery for AMOLED displays.

**Comment by g1lg1l** [comment]
I will add it soon! Stay tuned!:)

**Comment by g1lg1l** [comment]
Hey,Dark AMOLED mode It's now implemented...you can see it in this [commit](https://github.com/HoraApps/LeafPic/commit/c78e8255e41a44f8523f3e7b10d74c5833b1a2b0). 
if you note some bugs note it to me, hope you like it!Stay tuned!;)
