### ISSUE TITLE
not register as a photo gallery app

### ISSUE THREAD

**Issue by Astyan-42** [UnevenSoftware/LeafPic#131]
Hello I am not sure if it's a bug of leafpic but with an other gallery app I don't have it.
When I want to add an image in QKSMS it's give me the error message :
"App not found. Try to install an app of photo gallery !"

LeafPic v0.2.5
QKSMS 2.5.4
Both from F-Droid

**Comment by Astyan-42** [comment]
Same with the v0.2.6 of LeafPic (I just see the update)
Android 5.1, wiko pulp 4G, rooted, only the playstore as google app

**Comment by dnldsht** [comment]
Yeah I miss the pick intent, I will add it soon.

**Comment by revuwa** [comment]
If I remember correctly, this open source app: https://github.com/snowdream/android-imageviewer, I tried some time before, had this 'feature' and could server as a kind of template for it.
