### ISSUE TITLE
Photos not being moved

### ISSUE THREAD

**Issue by maddler** [UnevenSoftware/LeafPic#134]
I'm on an LG G4, Android 6.0 devices.
Whenever I try to move a picture that does nothing. I can delete pictures tho, so I assume that's not a permission related issue.

I'll try to provide LogCat output asap (got to disable that because an LG issue with logdaemon).

Leafpic version 2.6.

Thanks!
William

**Comment by iasgair** [comment]
I just moved a picture. It first appeared as if nothing happened, but when I do a refresh (slide/pull down the screen, if you know what I mean), the picture has moved. (Android 5.1)

Have you tried a refresh after the moving? If so, maybe the developers can add an automatic refresh after executing a move/delete/... command - or would that refresh the entire database, which could take a while when there are loads of files.

**Comment by maddler** [comment]
Tried that. That's definitely not working for me. And just found that also copying images is failing.

**Comment by g1lg1l** [comment]
fixxed in this [release](https://github.com/HoraApps/LeafPic/releases/tag/v0.3.1), stay tuned!;)

**Comment by maddler** [comment]
hey! That's now working but... my Camera folder is not showing anymore.
Of course that's not in the exclude/hide list and no .nomedia file in there (that's showing correctly anywhere else). I jsut tested this briefly before leaving home, there could be other folders missing.

Cheers!
