### ISSUE TITLE
Dark black (night) theme

### ISSUE THREAD

**Issue by rugk** [UnevenSoftware/LeafPic#139]
Currently the dark theme still uses a grey background. Especially for AMOLED devices a really black theme (similar to FDroids one e.g.) would be nice.

**Comment by g1lg1l** [comment]
i have implemented The AMOLED theme some day ago! Didn't see it? Settings>Basic Theme>Amoled>Ok

**Comment by rugk** [comment]
I used the old FDroid version. Wonder why there still is this outdated version...
