### ISSUE TITLE
(Animated) gifv support

### ISSUE THREAD

**Issue by rugk** [UnevenSoftware/LeafPic#140]
Gifs should be shown animated. Most other gallery apps lack of this feature.

**Comment by dnldsht** [comment]
what do you mean with animated GIFs? LeafPic support gifs.

**Comment by AbdullZ7** [comment]
I think he's talking about "gifv" format
https://gfycat.com/about

**Comment by rugk** [comment]
> what do you mean with animated GIFs? LeafPic support gifs.

Oh, yes. I was not able to test it until now. I did not expected LeafPic to support gifs...

So:

> I think he's talking about "gifv" format
> https://gfycat.com/about

Okay, I am renaming this issue. :wink:
So let's just track support for "gifv" here. :smile:

**Comment by Nama** [comment]
Maybe handle also soundless mp4 files just like gif's and webm's. Telegram does this and it is awesome!
Soundless mp4's are often used as animated pictures like gifs, like on twitter, gfycat and imgur.

**Comment by tp0** [comment]
Isn't GIFV actually just .webm? That is already supported, at least for local files (enable internal player in settings).

**Comment by wyatt8740** [comment]
"gifv" is actually something else. It's a gzipped text file containing links to video files (usually .mp4 and .webm) and a .gif file. It's not an image in and of itself.

to read these urls in a unix-like environment, one can do `zcat /path/to/gifv_file.gifv`.
The format is always changing, too - it used to just be raw text, now it's gzipped.
edit:
the format changes depending on how you download it, I think. I used wget to get the gzip, but when accessed via a browser it is plaintext.
http://i.imgur.com/TxZfwgO.gifv for instance.
It's something imgur came up with to deal with Safari not being able to handle webm.

**Comment by Nama** [comment]
Yes, I saw "gifv" only on imgur and it is webm and mp4.

The gzip compression with wget and plain text on a browser might be, if the webserver has gzip enabled. The browser extracts it, wget not.

**Comment by wyatt8740** [comment]
To elaborate further, it's just HTML gzipped (via `wget` anyway).
[snipped because it's huge]
[http://pastebin.com/VsP8vDQg](http://pastebin.com/VsP8vDQg)

**Comment by rugk** [comment]
Does this mean it is fixed/implemented or what?

**Comment by dnldsht** [comment]
I'm not looking to implement this in the near future

**Comment by rugk** [comment]
Okay, so why do you reopen it then? Do you want to mark it for contributors ("help wanted") or was this accidental?
