### ISSUE TITLE
Menu buttons do not work

### ISSUE THREAD

**Issue by rugk** [UnevenSoftware/LeafPic#142]
The following buttons do nothing: 
- Local Folder
- Tags
- Timeline
- Wallpapers
- Donate

So said in another way: Only the settings and the about button work.

Cyanogenmod 13

**Comment by g1lg1l** [comment]
Didn't see the alert dialog "coming soon!"? We will do it when we can, now we must Fix something on localfolder!

**Comment by rugk** [comment]
I used the old FDroid version (where there was no such alert). Wonder why there still is this outdated version...
