### ISSUE TITLE
Top menu-bar disappears when trying to interact with any of the buttons.

### ISSUE THREAD

**Issue by framethrower** [UnevenSoftware/LeafPic#145]
No matter what button (Left-"Go Back"-Arrow, Share, Trash-Can, Circle-Arrow or vertical-dots) i press, nothing happens besides that the whole bar simply slides off the top of the screen.

Tested in version v0.2.6 & v0.2.7
on Device "LG L9 II D605"
Android-Version 4.4.2

Can i be of further assistance?
Thx, btw. I already seem to like this app more than QuickPic and Piktures...

**Comment by taranarmo** [comment]
Same issue.
Motorola Defy+, android 4.4.4

**Comment by MarkoIndaco** [comment]
Same problem to me.
Sony Xperia E4g , Android 4.4.4 [stock rom 25.0.A.2.31 - rooted]
ZTE Blade Apex 2 , Android 4.4.2 [rom Orange Hi 4G - rooted]

**Comment by TinfoilSubmarine** [comment]
Same issue.
Samsung Galaxy S3, Android 4.4.2 [Custom/Modified Stock ROM - rooted]

**Comment by framethrower** [comment]
The top menu is now (since v0.4) always concealed behind the picture i'm viewing. At least if the currently viewed pic is scaled up enough.
See this screenshot for example: ![screenshot_2016-06-21-20-51-32](https://cloud.githubusercontent.com/assets/788035/16242394/7ea562f8-37f2-11e6-8ed4-f5cb4071f439.jpg)

So the z-index/layering issues were "only" functional before but now they are visual as well.

Do you have any idea what the issue might be and could give me a hint on where to investigate in the code, cause i'd like to help, but sadly my android dev skills are tiny and years old. That's why i fear it might take me a long time if i dive blindly in.

What might be different on our devices? 
It obviously seems to work on the majority of the devices or otherwise this issue would have received a lot more attention by now.

**Comment by MarkoIndaco** [comment]
Il 21 giugno 2016 20:49:12 CEST, framethrower notifications@github.com ha scritto:

> The top menu is now always concealed behind the picture i'm viewing. At
> least i guess so, as i can glimpse at a few pixels of the blue bar when
> i "forcefully" zoom out.
> So the z-index/layering issues were "only" functional before but now
> they are visual as well.
> 
> Do you have any idea what the issue might be and could give me a hint
> on where to investigate in the code, cause i'd like to help, but sadly
> my android dev skills are tiny and years old. That's why i fear it
> might take me a long time if i dive blindly in.
> 
> What might be different on our devices? 
> It obviously seems to work on the majority of the devices or otherwise
> this issue would have received a lot more attention by now.
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/HoraApps/LeafPic/issues/145#issuecomment-227535207

For what i can say the issue it's about "not recognize tip" , i mean... when LeafPic open a photo, you can see it and zoom as weel. Also double-tip zoom works well. Then, when you once the upper menu-bar appears, but when you tip  on it (whatever menu-icon) it soon diassapper. LeafPic recognize the tip, but not the icon/function associated on it.
Thanks for you're effort.

**Comment by g1lg1l** [comment]
i'm looking to solve it, sorry for the late response but i'm very busy in these day.
Cheers. :beers:
