### ISSUE TITLE
Is the splash screen 'needed'?

### ISSUE THREAD

**Issue by revuwa** [UnevenSoftware/LeafPic#146]
Don't get me wrong, but would you consider to (optionally) disable the splash screen sometime in the future?
If this exists because of some background loading processes, I could life with it. But if not, it would be cool if there would be a way to disable it.

Keep it up.

**Comment by g1lg1l** [comment]
Don't think it would be possibile since the splash screen is used to start background process of loading medias!
But...we can try to think about something to do! Why dont like it?

**Comment by revuwa** [comment]
Thanks for the response, the first sentence is all I wanted to know.

> Why don't like it?

I wouldn't say that I don't like it; in contrast it looks good to me, but I tried to think which other app I use, uses splash screens and found none. So I just wanted to ask, because most people want to use their apps as fast as possible, and splash screens are cool for some kind of intro on the first start, but not really for every start, I thought. In this strict case, your splash doesn't take too long, and as I said, I could life with it.

Depending on your answer, I personally don't think there is a need to waste manpower for thinking about anything in that way.

Just one thing. It would be cool if the splash screen doesn't come up on opening pictures (with LeafPic) through external apps. I don't know if this is already the case, because I can't open pictures with external apps, for now: https://github.com/HoraApps/LeafPic/issues/130

By the way, thanks a lot for this awesome app and your enthusiasm!
This is the app, I'm waiting for several months, because I can use it on the FOSS Android OS named Replicant (http://www.replicant.us/) without the proprietary 3D acceleration blobs (OpenGL ES drivers), which made a search for a FOSS gallery app, (which doesn't depend on it) to an odyssey...

**Comment by coderkei** [comment]
Id just like to comment that if you an open an image from a file manager into leafpic, the splash screen doesnt show. Maybe you could disable the splash screen and loads the background processes at the same time the main UI is loaded

**Comment by coderkei** [comment]
Quickpic and other file managers do not have splash screens

**Comment by dnldsht** [comment]
Splash Screen came up only when the app start, if you open media with leafpic it won't came up
anymore

**Comment by rugk** [comment]
> Quickpic and other file managers do not have splash screens

I think this is just because these screens are a quite recent feature. Some apps tend to show a white screen or similar useless things when loading, so a splash screen is certainly better in this case.

**Comment by gabsoftware** [comment]
Don't get me wrong, I very like LeafPic, but this splash screen 3s delay is something that I could leave without. It's about 2 seconds more than other apps need to open on my phone (QuickPic and Cyanogenmod 13 gallery).

**Comment by rugk** [comment]
But AFAIK in this 3 seconds LeafPic loads...
So if there would be no splash screen there would be a white or black screen for three seconds.

You may actually ask _why_ it does load so long, but the splash screen itself is neither guilty for this loading nor would its removal make the app faster.

**Comment by gabsoftware** [comment]
Sure :-) So, why does it load for 3 seconds instead of 1 for other apps, and is there something that can be done to improve this load time?
