### ISSUE TITLE
Github: Please tag releases

### ISSUE THREAD

**Issue by rugk** [UnevenSoftware/LeafPic#149]
Please tag your releases, so they can be seen [on GitHub](https://help.github.com/articles/creating-releases/).

**Comment by dnldsht** [comment]
I'm gonna tag next releases, big update is coming

**Comment by rugk** [comment]
You're a contributor/author?
If so could you please add yourself publicly to https://github.com/HoraApps?

Otherwise one does not know you're the author of LeafPic as you do not have the "contributor label" in your issue comments. This can be quite confusing... :smile:

**Comment by dnldsht** [comment]
here is the first one https://github.com/HoraApps/LeafPic/releases/tag/v0.3.1
