### ISSUE TITLE
Is that a good idea to use non-free Google maps to show locations?

### ISSUE THREAD

**Issue by Almtesh** [UnevenSoftware/LeafPic#150]
That was there thing that shocked me in the app.

**Comment by licaon-kter** [comment]
Any ideas on how to handle this better? Link to OpenStreetMap?

**Comment by Almtesh** [comment]
Yes, for instance. It's not more complicated, and you will not have to hide the copyright.

**Comment by dnldsht** [comment]
@Almtesh Which is the better way to display a map? I know that google static maps isn't  so optimized.

**Comment by Almtesh** [comment]
I don't understand your question.
I think you can do the same as Google map, but with the OSM website, or the Mapquest one.

**Comment by licaon-kter** [comment]
Inspiration: https://github.com/k3b/APhotoManager/wiki/geographic-map

**Comment by dnldsht** [comment]
@Almtesh What's the problem with google maps?

**Comment by licaon-kter** [comment]
Besides of all the tracking?

Choices are nice, hence an OSM choice :)

Also, as one that published your app on F-Droid you understand that users there might not have/want (access) to Google stuff on their devices.

**Comment by dnldsht** [comment]
I will chose a valid alternative for the map

**Comment by iasgair** [comment]
That's great news. Thanks for looking into this.

I think this is an important point that you should get rid of Google maps. I suspect many fdroid users (including myself) are so happy that LeafPic exists because it is the first true open source gallery alternative.

OpenStreetMap should be a viable replacement. If you continue to use Google maps it might cause fdroid to add a red warning that LeafPic promotes non-free network services.

**Comment by rugk** [comment]
:+1: for OpenStreetMap.

Seriously I'm really surprised this app is not tagged with the [advertises non-free network services](https://f-droid.org/wiki/page/Antifeature:NonFreeNet) on FDroid as Google Maps clearly _is_ a non-free network service.
So better get rid of it before the app gets this tag. :wink:

**Comment by poVoq** [comment]
This would be fancy for rendering OSM: https://www.mapbox.com/mobile/

**Comment by poVoq** [comment]
I guess this would be the easiest to use?
https://github.com/osmdroid/osmdroid

In general it would be nice to not only have the small map preview in the details window, but to have a folder view that shows all the pictures as markers on a larger zoom/pan-able map. A bit like this desktop application: http://www.geosetter.de/en/

**Comment by licaon-kter** [comment]
@poVoq No, that would bring the need for another app, while a browser will be certainly available on all devices, just open a link to those coords in browser in OSM and be done.

Yes, that's nice, hey even expand that to edit coords, say maybe they're wrong, but it that in the scope of LeafPic?

**Comment by Almtesh** [comment]
No, don't put a link to a map in browser. Either leave the map in the same place in the app, or put a config to let the user choose where he wants the map (either in app, or in the browser).
You can also put the in-app map and when the user touches the map, it opens the browser.

**Comment by licaon-kter** [comment]
An in map web view is ok, right.

**Comment by poVoq** [comment]
I think it would be useful to see the locations of multiple pictures the same time on one map. For example to easily see the distribution of an item photographed or to see a track taken while taking pictures.

**Comment by Almtesh** [comment]
@poVoq it's off-topic, if you want this feature, please open a new issue.

**Comment by nikonakoneko** [comment]
I would really appreciate too the hability to choose the map provider. I don't remember the app but I already seen some that let you choose to use either gmaps or osm in their settings.

**Comment by Almtesh** [comment]
@soratobukuroneko the last and only application in which I saw that is Digikam.
If the Leafpic leave that choice in the settings, it will get the non-free network anti-feature.

**Comment by Almtesh** [comment]
No, for the moment, just replace the capture you did in Google Maps by the same in OSM, if you want to do more, see in further versions.

**Comment by dnldsht** [comment]
finaly i switched to open street map https://i.imgur.com/AP9G8TY.png 
if I add the possibility to choce the provider (google maps/OSM)  will I get the non-free network anti-feature?

**Comment by dnldsht** [comment]
check the [new version](https://github.com/HoraApps/LeafPic/releases/tag/v0.3.5) with OSM!

**Comment by Almtesh** [comment]
@DNLDsht I don't know, actually, you should have one about the usage of Maps, so I don't really know.

**Comment by dnldsht** [comment]
In the latest [release](https://github.com/HoraApps/LeafPic/releases/tag/v0.4) there is the option for chose the provider, I'm sorry guys but google maps is set by default because it is faster than others.

also added watercolor map!
