### ISSUE TITLE
Remember album list position 

### ISSUE THREAD

**Issue by licaon-kter** [UnevenSoftware/LeafPic#158]
Case:
- have multiple albums
- scroll to the 25-th
- open it 
- press back arrow
- you're back at the top of the list
- try to remember what album you opened last

**Comment by licaon-kter** [comment]
Fixed by https://github.com/HoraApps/LeafPic/pull/161/commits/400b7f87d16378c5060cc472295efbb5bae7dcee ?

**Comment by dnldsht** [comment]
Not with that commit but it is fixed
I'm waiting for some translations and I will release v0.3 with this issue
fixed

**Comment by licaon-kter** [comment]
This is fixed in 0.3.

Too bad the translations were not pulled yet, hopefully soon.
