### ISSUE TITLE
Picture orientation always landscape 

### ISSUE THREAD

**Issue by agodlydeciple** [UnevenSoftware/LeafPic#162]
When viewing image as a thumbnail the orientation of the photo is correct. The moment you go into any photo that is supposed to be portrait it always shows it in landscape. You have to manually rotate the photo for it to appear correctly.

**Comment by rugk** [comment]
If this is a duplicate what about linking to the original issue? (and closing this one)

**Comment by agodlydeciple** [comment]
from what I could tell searching through all the open and closed issues this was not a duplicate. I will search through again and link to a ticket and close this if I find it.

**Comment by dnldsht** [comment]
I think it is related with this [one](https://github.com/HoraApps/LeafPic/issues/118) can you check the orientation in your photo?

**Comment by agodlydeciple** [comment]
yup that seems to be the one. 

Please see issue #118 going forward.

Thank you @DNLDsht
