### ISSUE TITLE
External storage (SD) media not showing up

### ISSUE THREAD

**Issue by maddler** [UnevenSoftware/LeafPic#165]
Just upgraded on 0.3 /DCIM/Camera folder is not showing.
That's on my external SD.

Os: 6.0
Device: LG G4

**Comment by revuwa** [comment]
I have the same behavior after upgrading to v0.3 (over F-Droid) on my AOSP 6.0.1 @ Samsung i9300.
(I preventative cleared the app data, then - but this doesn't help in any way).
The [Local Folders] menu-point doesn't seems to include any media of the external storage (sdcard); and shows media of the internal storage only.

I though, it's probably an idea, to add an [External Folders] or something like that, for the external sdcard storage? 
This could lead to a better 'differentiation' of the media sources; if anybody else likes it?

**Comment by unsourced** [comment]
I second revuwa, none of the pictures on my external SD are showing up. This is on version 0.3.1.

Device HTC One M8, file path: /storage/[numeric sd card name]

**Comment by comamondo** [comment]
Same for me on Moto G 2

**Comment by dervomsee** [comment]
Same for me on my Cyanogenmod 13 LG G3 with LeafPic 0.3.5

**Comment by loubam** [comment]
Same for me, BQ X5, CM 12.1, LeafPic 0.3.1 & 0.3.5

**Comment by pulsar895** [comment]
Same for me with HTC10, Android 6.0.1 and LeafPic 0.3.1 and 0.3.5

**Comment by agodlydeciple** [comment]
Same for me with LG G3, Android 6.0.1 and LeafPic 0.3.1 and 0.3.5

**Comment by ghost** [comment]
wow having the same problem here for 0.3.5 - i thought this would be fixed in 0.3.5, now i have to downgrade again.
At least an option in the settings menu to include 'SD Media'

**Comment by dnldsht** [comment]
Hey guys I think I solved this issue, I tested it on my only device with SD card. 
Manufacturers handle bad SD card so can you test this [apk](https://drive.google.com/open?id=0B4G2W-xokbBrTzVZN0dZbzJOUEk) and give me a feedback?

**Comment by loubam** [comment]
Works!
Thank you
BQ Aquaris X5 & CM 12.1

**Comment by revuwa** [comment]
@DNLDsht Thanks alot, your debug version works.
(In case you don't know it: but the camera symbol doesn't work in this version).

**Comment by dnldsht** [comment]
@revuwa do you mean the floating action button? I was testing some stuff on permission and I forgot to restore the camera funcion.
very soon I will release a new version!

**Comment by revuwa** [comment]
@DNLDsht yes, I mean the floating action button. (Just din't know that this symbol hast that name)...

> very soon I will release a new version!

Great, I'm looking forward to it :-)

**Comment by dnldsht** [comment]
media will show up on [this release](https://github.com/HoraApps/LeafPic/releases/tag/v0.4), but I'm not sure if all operations will work so can you test stuff like copy/move on the sd?

**Comment by pulsar895** [comment]
> media will show up on this release, but I'm not sure if all operations will work so can you test stuff like copy/move on the sd? 

Impossible to delete items stored in SD card but I can see them with 0.4.

Thanks for your work!

**Comment by alexandre-lg** [comment]
> media will show up on this release, but I'm not sure if all operations will work so can you test stuff like copy/move on the sd? 

Impossible to delete items stored in SD card but I can see them with 0.4.

Thanks for your work!

**Comment by dnldsht** [comment]
@alexandre-lg can you try the trick mentioned in #201 and give me the feedback?

**Comment by pulsar895** [comment]
That works perfectly with the trick!

Thank you!

**Comment by loubam** [comment]
Rename and move works for me too after trick. Thank you!
