### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by nicolas-raoul** [UnevenSoftware/LeafPic#167]
It would be great if the app was available on F-Droid.
Cheers!

**Comment by iasgair** [comment]
It is:
https://f-droid.org/repository/browse/?fdid=com.horaapps.leafpic

Note that it's not the latest version (yet), as the fdroid team hasn't built that (yet).

**Comment by nicolas-raoul** [comment]
Oh sorry, great :-)
My repo was not up-to-date, that was my problem.
