### ISSUE TITLE
Square previews [Feature Request]

### ISSUE THREAD

**Issue by maddler** [UnevenSoftware/LeafPic#169]
Using rectangle previews is wasting screen estate. Being able to switch back to square previews would be nice.

Thanks

**Comment by dnldsht** [comment]
it's strange beacuse i added this feature in the last version, but i think this will be related with sreen width.
can you provite the resolution of your phone and how many columns do you have  when you are displaying the media of the album

EDIT: grammar

**Comment by maddler** [comment]
Sorry, forgot to mention.
LG g4 (2560 x 1440), Android 6.0.
I'm seeing 6 cols.

Cheers.

**Comment by dnldsht** [comment]
do you have this issue with the last [release](https://github.com/HoraApps/LeafPic/releases/tag/v0.4)?

**Comment by maddler** [comment]
Sorry, missed your question.
Yes, still same issue on 0.4.

Thanks!

**Comment by dnldsht** [comment]
@maddler can you sen me a screenshot?

**Comment by maddler** [comment]
Sorry, my bad! I was looking at the "folders" view. Within a the folder squared previews are being shown indeed.
Anyway, from a UI consistence, woudn't it make sense to have square preview for folders too?

Tks.
