### ISSUE TITLE
change column count programmatically

### ISSUE THREAD

**Issue by maddler** [UnevenSoftware/LeafPic#171]
# Hello, that would be nice to be able to change previews size. That would be great if that could be done on the flight while browsing for images (maybe using volume buttons).

Cheers,
William

**Comment by dnldsht** [comment]
I'm implementing this feature, it works well with volume buttons and quite well with pinch in/pinch out geasture. 
Should I save and use the number of columns globaly for all albums or save the columns count for each album?

**Comment by wyatt8740** [comment]
I'd add a preference for globally vs. 'per album', like how firefox saves zoom information with an about:config preference determining if it is per site.

**Comment by maddler** [comment]
Exactly.

**Comment by maddler** [comment]
I think being able to set that globally and to override at the album level 
would be nice to have.

**Comment by dnldsht** [comment]
set it globaly.

**Comment by brandonio21** [comment]
Should this be closed, then? Or shall we wait until we have per-album controls?

**Comment by dnldsht** [comment]
it will close automaticaly, when the commit is merged on master.
