### ISSUE TITLE
Create new folder doesn't work

### ISSUE THREAD

**Issue by Micha-Btz** [UnevenSoftware/LeafPic#172]
hi there,

select all pics you want take move from menu and choose new folder.
a little popup displays new folder but nothing happen.
Logcat tells me nothing helpful. Ver 0.3 from fdroid.

Micha

**Comment by g1lg1l** [comment]
We will do it soon, stay tuned!;)

**Comment by ghost** [comment]
I seem to have the same problem but does not write to external storage. meaning i choose photos from local storage folder and move to.. external storage and the photo stays there. doesnt move. seems like there is no write access to external storage. i dont know why its doing this? but this is on v.0.2.7 as 0.3 doesnt even SEE external storage. so im having quite a lot of issues with this.

**Comment by g1lg1l** [comment]
fixed with this [pull](https://github.com/HoraApps/LeafPic/pull/200). I will work for a better solution soon.

**Comment by Micha-Btz** [comment]
work for me
