### ISSUE TITLE
include orientation/direction in "details" (and later in map view) [feature request]

### ISSUE THREAD

**Issue by iasgair** [UnevenSoftware/LeafPic#174]
Hi,
I don't know about other camera apps, but open camera records the orientation (the direction in which one is looking when the picture is taken) as a three digit degree value (meaning, if you taking a picture looking due south, it will record "180°").

Is there any chance this could be added to the details menu?

And related to this, but not as a priority, but maybe something to bear in mind for the future, once the (open street) map view is implemented: 
could there be a symbol indicating the direction that the picture faces. Something along these lines:
![unnamed](https://cloud.githubusercontent.com/assets/18640575/15212816/e328406a-183a-11e6-986d-8e76121a9c85.jpg)
I don't know how easy this is, and it is really more a map issue than a LeafPic issue, but if one day you have time, energy and the will to do this, it would be really useful. Maybe I'm the only one, in which case, don't bother and I'd be happy with having the orientation in the details menu.

**Comment by dnldsht** [comment]
The orientation will be added in the details dialog, but I'm not able to
get the direction from the exif.
Where did you find this information?  I looked in the [exif interface](http://developer.android.com/intl/es/reference/android/media/ExifInterface.html)
and I didn't find it.

**Comment by iasgair** [comment]
Disclaimer: I'm not an expert, and I cannot program.

I'm not sure what you mean by orientation, that you will add to the details dialog. Do you mean landscape/portrait?

I think what I'm after is called direction. If I open an image that I know has the information on my computer, I can open an EXIF box (I'm using IrfanView) and that lists it as "GPSImgDirection" (in my test case the value is 113.48).
As comparison, longitute is listed as "GPSLongitude" and the the E/W is recorded in "GPSLongitudeRef". So, comparing that to your link, I would expect the direction to be saved in "GPS_Img_Direction" (or "GPS_ImgDirection"?). I don't understand Java, but if it is not in the list in the link, does that mean it cannot be read by this ExifInterface?

**Comment by dnldsht** [comment]
Orientation included in the last version, [check it out](https://github.com/HoraApps/LeafPic/releases/tag/v0.3.5)!
