### ISSUE TITLE
Zooming Problems

### ISSUE THREAD

**Issue by unsourced** [UnevenSoftware/LeafPic#175]
Phone: HTC One M8 (Android 6.0)
Screen Resolution: 1080 x 1920 pixels 
problem present in v0.2.5 - v.0.3.1

When "Delay load full-size image" is not selected, LeafPic will not display large images at full resolution. For example, if I select a 8000 x 8000 pixel png, and then zoom in as far as the app lets me, the image does not load fine details and everything is blurry. Furthermore, an image this size cannot be zoomed in all the way to 100% detail. I have also tried this on an image that is 3000x2077 and it also can not zoom in 100% or resolve detail at this level.

When "Delay load full-size image" is selected, LeafPic will load detail on large images so there is no blur. However, the same limitation in zooming exists, so with the 8000 x 8000 image I can not zoom in nearly enough to properly see most of this additional detail. On the 3000x2077 I can come much closer to zooming in all the way, but still cannot quite zoom in completely.

However, when "Delay load full-size image" is selected, regular images from the camera (2688 x 1520) have to be zoomed or they always look blurry. Without zooming in (even a tiny bit) they look blurry every time. This makes the "Delay load" option essentially useless for me, because I cannot see zoomed out images at full resolution. These same pictures look completely fine full size (zoomed out) when "Delay load" is not selected.

Summary:

Delay load full-size image:
- on: images are blurry when zoomed out fully, when zoomed in large images show more detail
- off: images look good when zoomed out fully, when zoomed in large images do not show full detail
- both: large images cannot be zoomed in all the way, the larger the image the less (proportionally) the image can be zoomed in

**Comment by dnldsht** [comment]
in the last [version](https://github.com/HoraApps/LeafPic/releases/tag/v0.3.5) i fixed display and zoom problems when delay for full-size image is on, now working to fix also when delay for  full-size image is off and can diplay also larger images

**Comment by Almtesh** [comment]
I made a snapshot and the png image shows a resolution of 0×0 in details.

**Comment by dnldsht** [comment]
I'm gonna close this issue since #225 is the only issue that isn't already fixed
