### ISSUE TITLE
pictures on sdcard not visible

### ISSUE THREAD

**Issue by omerule** [UnevenSoftware/LeafPic#176]
I updated to version 0.3.1.
Now the pictures on my sdcard are not shown.

Is it possible to add a directory to your libary?

Yours kindly
Omer 
The Netherlands

**Comment by dnldsht** [comment]
This is a duplicate #165 
I'm looking for get this issue solved. 
Also the possibility to add a directory is in my plan

**Comment by ghost** [comment]
Just to let people know that using downgrade version of 0.2.7 works for me until this gets resolved!. thanks
