### ISSUE TITLE
Feature Request: Paste image into an image.

### ISSUE THREAD

**Issue by Rbagman** [UnevenSoftware/LeafPic#178]
I don't know if you can do this...

I just installed F-Droid alpha7; background updating works great, but the app didn't seem to know that it had updated IceCat.

I took two screen shots:

https://imagebin.ca/v/2h2G404fuTlx
https://imagebin.ca/v/2h2FCbwGEAqI

(F-Droid and IceCat's about page), cropped and uploaded them and pasted the links into my post.

Being able to crop/save to clipboard and position/paste from clipboard into another screen shot would be a very nice feature, especially if you are allowed one image only.

This would also rock with Clip Stack (F-Droid).

**Comment by dnldsht** [comment]
I think you posted in the wrong place.
