### ISSUE TITLE
Since v0.3 EXTERNAL STORAGE NOT AVAILABLE.

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#179]
Well, ive pretty much summed it all up in my heading above.
Since upgrade to version 0.3 it doesnt pick up any external data i had., i deleted 0.3 and downgraded to v0.2.7.
Can someone please fix this? i thought we were improving on features not removing them?
Please guys, cause this is really a great and super fast app.
Another thing is also if you can make the scroll bar a little bit thicker and darker to be seen when scrolling for loads of pics. Thank you!!

**Comment by licaon-kter** [comment]
Android version? Device?

**Comment by ghost** [comment]
SORRY, this is a duplicate of https://github.com/HoraApps/LeafPic/issues/176

**Comment by ghost** [comment]
android version 6.0 for Xperia Z5 Dual E6683, v0.2.7 worked with no problems.
