### ISSUE TITLE
Scroll Bar needs to be darker and slightly thicker [Improvement - feature]

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#180]
Hi
It would be convenient to see the scroll bar in a visible colour such as black, currently i can see its transparent and it also disappears when you stop scrolling.
It would be better to see it being black in colour and SLIGHTLY thicker, then it can disappear when the user stops scrolling and reappear when the user starts scrolling.

What do you think?
This is the best photo app and most simplest and fastest of all. thank you !!

**Comment by g1lg1l** [comment]
I will Fix it soon.

**Comment by g1lg1l** [comment]
hey,
At the moment it's fixxed on my [repo](https://github.com/Mow3l/LeafPic), if you can't wait you can fork and compile it.
anyway i will look for a better way in the future.
- for **ScrollView** [this](https://github.com/Mow3l/LeafPic/commit/72159833db8a154eafcd94c749bf78afaabe50bd) commit.
- for **RecyclerView** [this](https://github.com/Mow3l/LeafPic/commit/51690f2696f77c4879486919d1e5a16aa9a394c4) commit. 

Note: if you know a better solution for the recyclerview tell me!
**Stay tuned!;)**
