### ISSUE TITLE
Image selection count does not reset

### ISSUE THREAD

**Issue by Valeria-AT** [UnevenSoftware/LeafPic#184]
If i select images in a folder, go back to the main menu and go to the folder a second time, the selection is gone but the count is not 0.
With this i can select e.g. 10/5 images.

LeafPic 0.3.1
Android 5.1.1
Xiaomi Redmi 3
Internal Storage

![screenshot_2016-05-15-13-16-19_com horaapps leafpic](https://cloud.githubusercontent.com/assets/11169020/15273612/de0c1950-1a9f-11e6-9913-f85b9c0b0894.png)

**Comment by dnldsht** [comment]
fixed in the last version, [check it out](https://github.com/HoraApps/LeafPic/releases/tag/v0.3.5)!
