### ISSUE TITLE
Operations should force refresh

### ISSUE THREAD

**Issue by licaon-kter** [UnevenSoftware/LeafPic#185]
Case in point: delete.

Eg. 
- have 5 pictures in a folder
- enter folder
- open picture 1
- look at picture 2 -> delete it
- look at picture 3 -> delete it
- hit back to exit picture view
- see that 5 thumbnails are there, although you've deleted 2 files
- pull to refresh, 3 thumbnails show now
- exit folder view to all albums view
- see that the folder info still says 5 pictures
- pull to refresh, folder info now says correctly 3 pictures

**Comment by Valeria-AT** [comment]
Indeed.
When you delete all pictures in a folder you see the "There is nothing to show" in the main menu too.
Here i deleted all pictures in "WhatsApp Images"
![screenshot_2016-05-16-15-45-17_com horaapps leafpic](https://cloud.githubusercontent.com/assets/11169020/15291324/90440c3a-1b7d-11e6-8076-1e873c080019.png)

**Comment by dnldsht** [comment]
fixed in the last release [check it out](https://github.com/HoraApps/LeafPic/releases/tag/v0.3.5)!
