### ISSUE TITLE
Move to hidden folder

### ISSUE THREAD

**Issue by RR1991** [UnevenSoftware/LeafPic#187]
I have found that I cannot move pictures from a visible to a hidden folder, and vice versa.

**Comment by g1lg1l** [comment]
There is a folder icon near the bottomsheet title! If you click here the hidden folder will be loaded!

**Comment by RR1991** [comment]
Oh, excuse my ignorance. Great app! Thank you.

**Comment by g1lg1l** [comment]
You are welcome!;)
