### ISSUE TITLE
Impossible to open picture in messages

### ISSUE THREAD

**Issue by Almtesh** [UnevenSoftware/LeafPic#188]
When I get a MMS, I can't open directly the picture with LeafPic.
I think that's pearhaps because the app needs to access the messages to do that, but I don't really know a lot about Android system and programming.

**Comment by phuyuk** [comment]
Same problem opening attachments in K9-email. LeafPic DOES launch, but doesn't load/show the image - just an empty, themed BG (White, Dark or Dark Amoled).

**Comment by Almtesh** [comment]
Oups, this issue is duplicate with #168, sorry.

**Comment by dnldsht** [comment]
I closed this issue presuming images from mms are displaed now.
@firecat53 reported no problems in v0.4 relase here #168

**Comment by Almtesh** [comment]
Actually, I just tested now, it still does not work and #168 is not the same problem.

**Comment by phuyuk** [comment]
I hate to throw a wrench into this, but opening attached pics from K-9 (email) IS working with v0.4.  I haven't yet installed LeafPic on my phone, so i don't know if it's playing well with an SMS client.

**Comment by phuyuk** [comment]
Sorry folks - it appears that #168 was my problem, all along. My apologies for confusing the issue.

**Comment by dnldsht** [comment]
@Almtesh are you using the stock application for messages? are you able to give me the log?

**Comment by Almtesh** [comment]
No, I use neither the stock application, nor the CyanogenMod stock one. The stock one is very strange and I could'nt install the CM stock one, yet. I use QKSMS instead.
I can access the log, but I can't understand how they work and thy are very verbose, do you want me to grep the log?

**Comment by dnldsht** [comment]
@firecat35 use QKSMS and doesn't have problems.
by the way I would be happy if you provide the log during the crash so I can investigate

**Comment by Almtesh** [comment]
I will provide you, but I must resolve a problem with MMS and QKSMS.

**Comment by Almtesh** [comment]
I can't open QKSMS anymore, I try briefly with another SMS application (if I find one) and if it works, I close this issue.

**Comment by Almtesh** [comment]
I think this is the log you want :

W/art     (16961): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
W/System.err(16961): java.lang.NullPointerException: Attempt to get length of null array
W/System.err(16961):    at com.horaapps.leafpic.Base.Album.updatePhotos(Album.java:79)
W/System.err(16961):    at com.horaapps.leafpic.Base.Album.<init>(Album.java:64)
W/System.err(16961):    at com.horaapps.leafpic.PhotoPagerActivity.onCreate(PhotoPagerActivity.java:101)
W/System.err(16961):    at android.app.Activity.performCreate(Activity.java:5990)
W/System.err(16961):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
W/System.err(16961):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
W/System.err(16961):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
W/System.err(16961):    at android.app.ActivityThread.access$800(ActivityThread.java:156)
W/System.err(16961):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
W/System.err(16961):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(16961):    at android.os.Looper.loop(Looper.java:211)
W/System.err(16961):    at android.app.ActivityThread.main(ActivityThread.java:5371)
W/System.err(16961):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(16961):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err(16961):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:945)
W/System.err(16961):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:740)

I don't understand why these logs are so verbious, but I can recognize a java exception.

**Comment by Almtesh** [comment]
@dnldsht Sorry, I can't tell you if it works since I changed my mobile operator and I can't recieve MMS anymore. I think more and more to rollback to the previous one, but I don't know.

**Comment by alekksander** [comment]
I experience the same bug with QKSMS and LeafPic.
