### ISSUE TITLE
Include direction in details

### ISSUE THREAD

**Issue by iasgair** [UnevenSoftware/LeafPic#192]
Hi,
sorry if I am annoying, but this is a continuation of issue #174 , which I cannot reopen.

Maybe I wasn't clear about what I intended with that issue, I apologise and blame it on not being a native speaker. You have included **orientation** in the details dialogue (which in my case always returns the value "0"). 
What I was really after is the **direction**, meaning the compass direction in which the image view is facing (i.e. the compass direction I was looking when I took the picture). From using the EXIF dialogue on my computer (IrfanView on Windows) I have found that this direction is recorded in the EXIF data (see post in issue #174).

It would be great if this could be implemented.
Thanks for the great work, I love LeafPic.

**Comment by brandonio21** [comment]
@iasgair  @dnldsht  - Are you still looking for this feature? I'll see if I can't take a crack at it tonight.

**Comment by iasgair** [comment]
I would love it.

**Comment by brandonio21** [comment]
@iasgair  - Sorry for the delay .. been busy. Will work on it tomorrow :)
