### ISSUE TITLE
draggable scrollbar (for fast scrolling in folders with many files)

### ISSUE THREAD

**Issue by revuwa** [UnevenSoftware/LeafPic#194]
If I have a folder with hundreds or thousands of files and want to scroll to the end of the file list, I nearly break my thumb by hectically scrolling to the bottom.

I saw a feature, for example in the regular Android contacts app, where you could grab the scrollbar and move it simply (and lightning fast) to the bottom.

I'm not hundred percent sure, but I think this feature is named "draggable scrollbar", and (hopefully) shouldn't be that hard to enable it: https://stackoverflow.com/questions/18254370/how-to-add-draggable-scrollbar-to-scrollview-listview-in-android

I would love to see that kind of feature sometime in the future in your great app.
Thanks in advance for any support in that case.

**Comment by g1lg1l** [comment]
I will work on it soon! stay tuned!:)
