### ISSUE TITLE
GitHub repo not up to date

### ISSUE THREAD

**Issue by licaon-kter** [UnevenSoftware/LeafPic#195]
Compare:
https://github.com/HoraApps/LeafPic/blob/master/app/src/main/res/values/strings.xml
with 
https://crowdin.com/project/leafpic

Please push here first.

**Comment by dnldsht** [comment]
I'm sorry I was working on my fork.
I created a [develop branch](https://github.com/HoraApps/LeafPic/tree/develop) that is up to date.
