### ISSUE TITLE
Need image sorting settings

### ISSUE THREAD

**Issue by wyatt8740** [UnevenSoftware/LeafPic#196]
I often browse files in a file manager sorting by file name. I have images set to open in leafpic so I can swipe back and forth and view other images in the directory. However, leafpic sorts by modification date (I think), and there is no setting to change this behaviour that I can find. Please consider implementing some more options, like sorting by name or maybe by filetype.

**Comment by wyatt8740** [comment]
for now I'm using a horrid little hack to accomplish what I want by doctoring modification times, but I'd love to have this done right instead.

```
#! /system/bin/sh
#hack to sort photos by name in programs that use dates.
export ITERSEC=59
export ITERMIN=59
export ITERHOUR=23
typeset -Z 2 PADSEC
typeset -Z 2 PADMIN
typeset -Z 2 PADHR
PADSEC=$ITERSEC
for file in *; do
    PADHR=$ITERHOUR
    PADMIN=$ITERMIN
    PADSEC=$ITERSEC
    PADNUM=$PADHR$PADMIN$PADSEC
    touch -t 19700101.$PADNUM "$file"
    ITERSEC=`expr $ITERSEC - 1`
    if [ "$ITERSEC" -eq "0" ]; then
        ITERMIN=`expr $ITERMIN - 1`
        ITERSEC=60
    fi
    if [ "$ITERMIN" -eq "0" ]; then
        ITERHOUR=`expr $ITERHOUR - 1`
        ITERMIN=60
    fi
done
```

Or reverse order:

```
#! /system/bin/sh
#hack to sort photos by name in programs that use dates.
export ITERSEC=1
export ITERMIN=0
export ITERHOUR=0
typeset -Z 2 PADSEC
typeset -Z 2 PADMIN
typeset -Z 2 PADHR
PADSEC=$ITERSEC
for file in *; do
    PADHR=$ITERHOUR
    PADMIN=$ITERMIN
    PADSEC=$ITERSEC
    PADNUM=$PADHR$PADMIN$PADSEC
    touch -t 19700101.$PADNUM "$file"
    ITERSEC=`expr $ITERSEC + 1`
    if [ "$ITERSEC" -eq "60" ]; then
        ITERMIN=`expr $ITERMIN + 1`
        ITERSEC=0
    fi
    if [ "$ITERMIN" -eq "60" ]; then
        ITERHOUR=`expr $ITERHOUR + 1`
        ITERMIN=0
    fi
done
```

**Comment by dnldsht** [comment]
Yeah LeafPic sort images by date modified by default.
now you can sort your media only if you open albums from the app
I'm gonna add that option also when you are on the single photo view (ViewPager), so you can sort them even if you open from another app.

EDIT: I will also add filetype option!

**Comment by wyatt8740** [comment]
That sounds great; I'll be glad when I can stop forging modification times.

Perhaps a setting to control whether sorting is 'case sensitive' would be helpful, too, since file managers handle that differently?

Thanks for the fast response!

**Comment by dnldsht** [comment]
check out [new version](https://github.com/HoraApps/LeafPic/releases/tag/v0.4) sort available on the single photo view also file type option!

I dont get why file managers are key sensitive when sorting stuff IMO it has no sense.
