### ISSUE TITLE
Issues with operations (copy/move) on SD card

### ISSUE THREAD

**Issue by dvrax** [UnevenSoftware/LeafPic#201]
Just lost a few pictures of mine this morning after updating. For the record, moving pictures to my SD card never worked for me, but deleting them and not moving is new.

**Device:** Samsung Galaxy S4 (non-rooted, SCH-R970)
**OS:** Android 5.0.1

**Comment by dnldsht** [comment]
@NoTroop I'm sorry for your lost, this shouldn't happen.
Can you long press the camera FAB then you have to chose the sd card from the drawer then click select all on the root of the sd card (if the steps aren't so clear look at [this picture](http://i.imgur.com/NOAJ4vu.jpg)) this should give LeafPic the permission to write on sd. after that try do do operations like copy or move (try with not important images for avoid other lost)

**Comment by dvrax** [comment]
@dnldsht That fixes the issue, although deleting them instead of just doing nothing is not preferred(doing nothing is what happened before the .4 update). Thanks for the quick reply.

**Comment by dnldsht** [comment]
@NoTroop the move operation should delete images only if the copy has success. I'm gonna look to solve this Issue.

**Comment by ghost** [comment]
Hellooo 👋 

Nice work so far. 
Can't delete any pictures on my external SD Card. 

I'm using a note 4 910u on cm13. 
The permissions for the app are right. Don't know what the problem is. 

Cheers, 

Dan

**Comment by dnldsht** [comment]
I worked on this issue and I think I get it fixed (I tested it only on a device with Lollipop), are you able to build the develop branch and give me a feedback? otherwise here are an [apk](https://drive.google.com/file/d/0B4G2W-xokbBrTFF0ODVNZlE5LXM/view?usp=sharing).

**Comment by dvrax** [comment]
@dnldsht I ran the apk you gave and tried it out and it prompted me for SD-card access and did not delete the picture (even when I selected the wrong storage to give it access to). But it never successfully moved it either, it just kept prompting for permissions on the SD card no matter what. The actual issue of deleting on a failed move seems to be gone though.

**Comment by hrslkvc** [comment]
I have the same issue as @NoTroop It prompts me for the permission but when i select SD card it just goes back and when i try to delete a picture it asks for permission again and doesn't delete it after.

I'm also on the galaxy s4 I9505 running stock lollipop 5.0.1

**Comment by Sam-C-Dev** [comment]
I just tried to Move about 15 pictures out of my Camera Folder, into a new Folder.  However, this deleted ALL pictures from my Camera folder, and there are NO pictures in the destination folder. Every photo I have - GONE. I'm looking all over the phone to see if they could have been moved to a TMP folder or something, but nothing is coming up. I'm really not sure I trust this app yet. URGHH
