### ISSUE TITLE
Using a normal font for leafpic logo

### ISSUE THREAD

**Issue by BedHead911** [UnevenSoftware/LeafPic#202]
Im using the latest version from f droid v0.4
I thought that the leaf pic branding or logo in the splash screen and the side menu has a really strange font. I think that using a regular font for leafpic will look more clean and give us a consistent user experience.

**Comment by g1lg1l** [comment]
Please consider to send a mail about this kind of things! And don't open a issue, by the way i will look for a cleaner font soon! Stay tuned!
