### ISSUE TITLE
Display filename of videos

### ISSUE THREAD

**Issue by Valeria-AT** [UnevenSoftware/LeafPic#203]
It would be great if I could see the filename of a video without going into the folder, pick one video and go to the "Details" for each videofile.
Background: I watch a tv-series on my phone and the preview pictures are not meaningful if i want to see the next episode or want to complete a started episode.

**Comment by dnldsht** [comment]
@Theobald93 in which location is better on the [grid view](https://i.imgur.com/Wyzzdir.jpg) or on [single media view](https://i.imgur.com/Ai5YpQ2.png).

**Comment by Valeria-AT** [comment]
In my case on the grid view of course.
Thanks for the quick response (:
