### ISSUE TITLE
Heading hides top of the image

### ISSUE THREAD

**Issue by PF4Public** [UnevenSoftware/LeafPic#204]
While opening image, heading bar hides the top of the image (the one with buttons with the image number).
Frustrating thing is that neither image could be zoomed out to fit beneath the heading, nor it could be pulled down out of heading. Even zooming in keeps hiding the top of the image. It looks like not only image is tiled under the heading, but part of it is under the topmost notification bar also.

**Comment by dnldsht** [comment]
@PF4Public have you tried to make a single click on the photo it should go on full screen. 

PS it is called toolbar.

**Comment by PF4Public** [comment]
Indeed it does. Sorry, not a bug.
