### ISSUE TITLE
Icons being cut in drawer

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#205]
Icons are being cut in the drawer and also the checkmark icon suffers the same when you select a folder. Usually this happens as soon as I open leafpic.

Device: Nexus 5X - Stock - Unrooted

**Comment by g1lg1l** [comment]
Can you provide me a screen of the issue?

**Comment by ghost** [comment]
On the drawer:
https://dl2.pushbulletusercontent.com/Ug0FXgoiXtveSc2dVtOtTxFFLimz7toJ/Screenshot_20160617-194226.png

When selecting folders:
https://dl2.pushbulletusercontent.com/1qa30ieyruYua9qCpb9mrYPWaDhqiMot/Screenshot_20160617-194236.png

When selecting pictures:
https://dl2.pushbulletusercontent.com/3o1zlkJrQvZMUIKsnXqAmJrSg6xYZshp/Screenshot_20160617-194812.png

They fix themselves after a while if I don't do anything, or like it happened just now, they fixed themselves when I took the screenshots, but if I close the app and re-open it, it comes back. It's been affecting it since the version before the one now on F-Droid.

**Comment by g1lg1l** [comment]
Really strange, i will look for a solution soon!
