### ISSUE TITLE
hidden folder and .nomedia behave strangely

### ISSUE THREAD

**Issue by TheKK** [UnevenSoftware/LeafPic#208]
Here's the scenario
- I have a hidden directory, `/picture/.youCantSeeMe`
- there's some other directory under it, like `/picture/.youCantSeeMe/a`

So the problem is, I can't see images under `/picture/.youCantSeeMe/` and `/picture/.youCantSeeMe/a` unless there's `.nomedia` in it.

ps. `/picture/.youCantSeeMe/` could be categorized into **hidden folder** correctly.

**Comment by licaon-kter** [comment]
The problem is only with folders starting with a dot or with every folder?

**Comment by dnldsht** [comment]
@TheKK I chose to not consider as hidden folder folders that start with the dot because usually they contains useless stuff like cached images. I'm gonna consider also them as hidden folder. 

PS for the moment only folders with .nomedia file inside are considered as hidden folders
