### ISSUE TITLE
404 image

### ISSUE THREAD

**Issue by deavmi** [UnevenSoftware/LeafPic#209]
Don't display a 404 image over developer's images before image has loaded but rather a stock default unset profile picture placeholder image. Like those ghost profile pics. I forgot how to describe it.

**Comment by g1lg1l** [comment]
you're right, I will change it.

**Comment by deavmi** [comment]
It can sometimes be incorrect as 404 doesn't mean "Image loading". Thanks :smile:

**Comment by deavmi** [comment]
You guys should consider creating a custom ROM considering how beautiful your design is and how usable Leaf pic is currently. You could re-write the stock android apps.

**Comment by g1lg1l** [comment]
LeafPic is our First app, we are in a learning process. Maybe in the future, if the team widens!

Ps: thanks for your support, we realy apreciate it!

**Comment by deavmi** [comment]
Pleasure.

Same here. I am still learning how to make lexers. It is fun. :)

On 19 June 2016 2:59:49 PM SAST, Gilbert Ndresaj notifications@github.com wrote:

> LeafPic is our First app, we are in a learning process. Maybe in the
> future, if the team widens!
> 
> Ps: thanks for your support, we realy apreciate it!
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/HoraApps/LeafPic/issues/209#issuecomment-226996085

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dnldsht** [comment]
@deavmi did you noticed the 404 image playing aroud with filters?

**Comment by deavmi** [comment]
@dnldsht No. When I went to the about screen and saw the two developer profile pictures the first profile picture was a red background with white text 404 image and then later changed into an actual profile picture.

**Comment by PF4Public** [comment]
FWIW I have a folder with `.gif` subfolder and the top-most is displayed with 404. I think it is because LeafPic is confused with `.gif` folder.

**Comment by dnldsht** [comment]
@PF4Public I'm gonna fix this. Thanks for the report I miss this case.

**Comment by deavmi** [comment]
Awesome. :)

**Comment by AbdullZ7** [comment]
I prefer this :D 

<img src="https://i.imgur.com/5IeMHXB.gif" alt="GIFV" height="300">

**Comment by deavmi** [comment]
@AbdullZ7 LOOL
