### ISSUE TITLE
Rotate button

### ISSUE THREAD

**Issue by deavmi** [UnevenSoftware/LeafPic#210]
I think the rotate button should not bring up a menu but just rotate by 90 degrees.

**Comment by Valeria-AT** [comment]
In this menu the function "flip (horizontal/vertical)" would be nice ^^

**Comment by deavmi** [comment]
Maybe the default orientation of the flip can be defaulted as the one last used. Comment if you don't know what I mean.

**Comment by Valeria-AT** [comment]
I would suggest: If we press the button for a short timespan the picture will rotate right 90° but if we press the button for a long timespan the menu appears with:
Rotate right 90°
Rotate left 90°
Rotate 180°
Flip horizontal
Flip vertical

To make that clear: I am no developer of this app.

Just tested the rotate functions in Leafpic 0.4 on pictures on the internal storage:
Nothing happens. Bug?

Edit: It works when I ENABLE "Delay load full-size image". (But i always have this function disabled because i have a lot of pictures that have the same resolution as my screen and they are blurry when enabled)

**Comment by dnldsht** [comment]
@Theobald93 the rotate option is not working yet. I would consider your suggestions, this feature hasn't the higher priority for the moment, also I'm pretty busy these days.
Cheers!

EDIT: it works if you disable delay loading full image in settings.

**Comment by deavmi** [comment]
@Theobald93 This sounds like a great idea.

**Comment by deavmi** [comment]
OK.

On 21 June 2016 6:40:45 PM SAST, Donald Shtjefni notifications@github.com wrote:

> @Theobald93 the rotate option is not working yet. I would consider your
> suggestions, this feature hasn't the higher priority for the moment,
> also I'm pretty busy these days.
> Cheers!
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/HoraApps/LeafPic/issues/210#issuecomment-227498440

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by deavmi** [comment]
By "nothing happens" do you mean it is not writing the new image to disk?

On 21 June 2016 6:33:36 PM SAST, Theobald93 notifications@github.com wrote:

> I would suggest: If we press the button for a short timespan the
> picture will rotate right 90° but if we press the button for a long
> timespan the menu appears with:
> Rotate right 90°
> Rotate left 90°
> Rotate 180°
> Flip horizontal
> Flip vertical
> 
> To make that clear: I am no developer of this app.
> 
> Just tested the rotate functions in Leafpic 0.4 on pictures on the
> internal storage:
> Nothing happens. Bug?
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/HoraApps/LeafPic/issues/210#issuecomment-227496581

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Valeria-AT** [comment]
"Delay load full-size image" enabled:
The "displayed picture" does not rotate and the "real picture file" does not change too. 

"Delay load full-size image" disabled:
The "displayed picture" does rotate but the "real picture file" does not change.

But @dnldsht already explained that this functions is not implemented yet.

**Comment by deavmi** [comment]
Okay. :smile:

**Comment by wyatt8740** [comment]
@Theobald93 I do not like the idea of relying on the user knowing that holding on a button will bring up additional options. A menu is far more foolproof. Alternately use separate discrete buttons for different kinds of transformations.

**Comment by Valeria-AT** [comment]
@wyatt8740 Fine for me. Today's practice is to hide every "special action" and I do not like it either. I prefer a simple menu too. But it is not as fancy, "smart" and modern which is "important" in these days^^

**Comment by wyatt8740** [comment]
@Theobald93 Projects like SeaMonkey still exist, so I think a fair number of people still prefer function over form.

http://i.imgur.com/zsYmHsx.png

(my browser of choice)
