### ISSUE TITLE
Scrollable View changes position on Device Rotation

### ISSUE THREAD

**Issue by reverse-unina** [UnevenSoftware/LeafPic#213]
When I perform these sequences of events, the scroll view on screen goes back to the top:

Sequence 1:
1. Open Side Drawer
2. Click on About
3. Scroll Down
4. Orientation Change

Sequence 2:
1. Open Side Drawer
2. Click on Donate
3. Scroll Down
4. Orientation Change

Sequence 3:
1. Open Side Drawer
2. Click on Settings
3. Scroll Down
4. Orientation Change

**Comment by dnldsht** [comment]
Fixed orientation change problems, also dialog won't disappear any more.
