### ISSUE TITLE
Support for Android 4.0

### ISSUE THREAD

**Issue by leighayanid** [UnevenSoftware/LeafPic#215]
support for API 15?

**Comment by g1lg1l** [comment]
We start the development only for lollipop and then we decided to support even KitKat! We have a lot of issues on kitkat and then i don't think we will support android 4.0...but if someone will help us in the future maybe we could think about it!
At the moment i say no, i'm sorry!

**Comment by leighayanid** [comment]
sad to hear that. Anyway, this is a great library. Keep up the good work buddy.

**Comment by navidei** [comment]
@Mow3l If you could mention the parts that are not supported in lower API versions maybe I could help to make this great library available for older devices.
