### ISSUE TITLE
Feature Request: Advanced Folder usage - Select images and change folder view size

### ISSUE THREAD

**Issue by BlackLotus** [UnevenSoftware/LeafPic#218]
A feature to long press an image and select multiple images pulling down would be nice.
Also a feature to pinch zoom in and out in the folder view to show more/less thumbnails would be awesome.

**Comment by dnldsht** [comment]
> A feature to long press an image and select multiple images pulling down would be nice.

There is a similar [feature](https://vimeo.com/173155276).

> Also a feature to pinch zoom in and out in the folder view to show more/less thumbnails would be awesome.

this is a duplicate check out #171

**Comment by BlackLotus** [comment]
Thx for the answer.
Maybe you can enable the wiki so features like this can be documented.
Anyway closing the issue (I would mark it as duplicate)
