### ISSUE TITLE
[Bug] getting blank activty when opening notification with open as picture intent

### ISSUE THREAD

**Issue by xtj-9182** [UnevenSoftware/LeafPic#219]
1. I was using opengur (https://github.com/Kennyc1012/Opengur) to download a picture
   opengur will create a notification that you can click and then android asks you to select a
   picture app to open this picture
2. choose leafpic to open the picture
3. Leafpic opens with blank activity

![2016_06_27_22 13 25](https://cloud.githubusercontent.com/assets/9414008/16465665/31485778-3e40-11e6-8f8c-a0c3649e725a.png)

Edit: this only happens with pictures not with gifs.

**Comment by dnldsht** [comment]
I'm gonna take a look at this as far as I can! 

EDIT: @xtj-9182 fixed this also for images, but since @Kennyc1012 share a custom content provider even though images are saved in the internal storage, I'm not able to share/delete/move and other stuff with this kind of data;

**Comment by xtj-9182** [comment]
> but since @Kennyc1012 share a custom content provider even though images are saved in the internal storage, I'm not able to share/delete/move and other stuff with this kind of data;

isn't that an opengur bug ? I only requested that it's possible to view images when tapping on the notification.

**Comment by Kennyc1012** [comment]
Opengur uses a custom file provider as outlined [here](https://developer.android.com/reference/android/support/v4/content/FileProvider.html). The Share Uri is also given read/write permission as shown [here](https://github.com/Kennyc1012/Opengur/blob/master/src/main/java/com/kenny/openimgur/services/DownloaderService.java#L100).

EDIT: Whoops, seems that only the share intent has read/write and the view intent has read only, not sure if that matters as @xtj-9182 is just stating he wants to only view the image.

**Comment by dnldsht** [comment]
@Kennyc1012 imo it should be bettere to share an Uri like file://... since files are saved on the storage so other apps can handle the result better.

EDIT: @xtj-9182 [here](https://github.com/HoraApps/LeafPic/commit/77fffbd9e0e95fe7c4f8f5b61e6e42bf77440360) you can find your problem fixed.
@Kennyc1012 you should share the Uri defined at line [94](https://github.com/Kennyc1012/Opengur/blob/master/src/main/java/com/kenny/openimgur/services/DownloaderService.java#L94).

**Comment by Kennyc1012** [comment]
@dnldsht No, the main reason behind this is that passing a file uri (file:///) will require the read/write storage permission, where as reading the file provider uri will not. Along with the permission issue, it is more secure to use a [File Provider](https://developer.android.com/reference/android/support/v4/content/FileProvider.html). Although your app (I'm assuming) has this permission, others might not which may causes issues there.

Also see [this blog post](https://commonsware.com/blog/2016/03/14/psa-file-scheme-ban-n-developer-preview.html)  about how the file scheme is being banned in forth coming Android versions

**Comment by xtj-9182** [comment]
> but since @Kennyc1012 share a custom content provider even though images are saved in the internal storage, I'm not able to share/delete/move and other stuff with this kind of data;

sorry just reread what you wrote and I think I get it now however that seems to be true for other image viewers too and they can handle opening it just fine too. I specifically checked if I could open it with other image viewers too. Anyway latest commit fixed it thx.
