### ISSUE TITLE
Performance/rendering issue with certain kind of photos

### ISSUE THREAD

**Issue by tp0** [UnevenSoftware/LeafPic#226]
Leafpic 0.4 (from F-Droid)
Lollipop 5.1.1
Motorola Moto G 3rd Gen

This is a pretty weird issue but finally I managed to figure out at least this repro, assuming it is not just my device:
- download this: [01.jpg](https://dl.dropboxusercontent.com/u/13766493/shared/leafpic/01.jpg) (just a photo of a wall), make at least one copy of it so that you can swipe previous/next and put them into a new folder somewhere where Leafpic scans them
- open Leafpic and open one of the photos
- swipe left/right and observe the poor performance (also affects zooming and even the UI becomes sluggish)
- tap back
- now put phone in landscape mode and open one of the photos again
- performance is normal while swiping, and if you now change between landscape and portrait, performance remains normal

"Delay load full-size image" is disabled, because that other bug (#175). If it is enabled, then I get get the blurry zoomed out images and performance is ok. Related?

If the photo was rotated 90 degrees (I mean the file, not rotated in Leafpic) then performance would be ok in landspace mode, but poor in portrait mode respectively, so issue is probably not the landscape mode itself.

The weird part is that I can not repro this with just any photo. I even googled and downloaded several high-resolution samples (even bigger resolution and higher MPs than above example photo). However, I can repro this with almost any photo my device takes. Other than them being usually pretty noisy, I have no idea what makes them so special.

**Comment by dnldsht** [comment]
@tp0 in some photos there is a thumnail inside, in your case I think the thumnail have a low resolution and so you get this blury effect.
I'm gonna look for a better management for thumnails and it is not related with #225

**Comment by tp0** [comment]
Oops, I linked the wrong issue. I meant #175

**Comment by dnldsht** [comment]
@tp0 I thought that you have this issue on the GridView but reading again your post I think that you were talking about the ViewPager(single photo view) is it true?

**Comment by tp0** [comment]
@dnldsht Yes, single photo view.
