### ISSUE TITLE
Delay loading full-size image regardless of zoom

### ISSUE THREAD

**Issue by touzainanboku** [UnevenSoftware/LeafPic#227]
Currently, you have two options:
1-  Have "Delay load full-size image" disabled:
- Advantage: higher image quality is displayed
- Disadvantage: longer waiting time

2- Have "Delay load full-size image" enabled:
- Advantage: shorter waiting time
- Disadvantage: lower quality image is displayed

My suggestion is for the app to initially load a lower resolution image to avoid a long waiting time, and then proceed to load the full size image, regardless of whether the user zooms in or not. This way you get both advantages - shorter waiting time and higher quality image being displayed.

**Comment by dnldsht** [comment]
@touzainanboku I'm gonna look for get it working like what you said. I also hate that option :D

**Comment by squiggie** [comment]
I see you're using Glide. Assuming you're using glide in the code where this is used, you can easily load a thumbnail request that should satisfy this. Take a look at https://futurestud.io/blog/glide-thumbnails

**Comment by wyatt8740** [comment]
I'd like this, although I'd also like to keep the current option of always loading the full resolution immediately, since loading one image is faster than loading a smaller one before a larger one.

It's like the old progressive-vs-'interlaced' jpeg argument.
