### ISSUE TITLE
How to show the map of a picture?

### ISSUE THREAD

**Issue by rugk** [UnevenSoftware/LeafPic#232]
How can I show the location saved in the exif data? I see it is possible, but I don't know how.

**Comment by dnldsht** [comment]
It detect it from the exif and automatically display it but it needs Internet.

**Comment by rugk** [comment]
It has. Where exactly does it display this?

**Comment by dnldsht** [comment]
In the details dialog.

**Comment by rugk** [comment]
Okay, thanks.
