### ISSUE TITLE
OpenStreetMap does not work

### ISSUE THREAD

**Issue by rugk** [UnevenSoftware/LeafPic#233]
This is what it shows:
![leafpicosm](https://cloud.githubusercontent.com/assets/11966684/16886820/a89bcfb0-4ad6-11e6-860d-5df0d278baa5.png)

Additionally the titles are accessed over HTTP, which is not that nice.

**Comment by rugk** [comment]
See http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

**Comment by rugk** [comment]
Alternative providers: https://switch2osm.org/providers/
IMHO https://www.mapbox.com/ has really nice maps...

**Comment by dnldsht** [comment]
@rugk I'm gonna take a look at mapbox.com, it looks very nice.

**Comment by rugk** [comment]
Maybe it is also faster (or at least nearly as fast) as Google Maps, so you can set it as default. :smiley:

**Comment by dnldsht** [comment]
@rugk added maps from mapbox.com also a dark and light version! just wait for the new release.

**Comment by rugk** [comment]
So is this now faster (or at least as fast) as/than Google Maps, so can you enable Mapbox by default, please?

**Comment by dnldsht** [comment]
I'm gonna set it as default, and yeah it is faster as Google maps.

**Comment by rugk** [comment]
Usually issues are only closed when the issue is actually fixed, so if it is currently "in progress" the issue should stay open. You can then [let issues close](https://help.github.com/articles/closing-issues-via-commit-messages/) when a PR is merged/commit is done.

**Comment by dnldsht** [comment]
@rugk I was just make some clean on the issue section, so since it is fixed on the develpo branch i thought that i can close it! 
by the way next issues will be closed with commit messages!

**Comment by rugk** [comment]
> so since it is fixed on the develpo branch i thought that i can close it! 

In this case it is okay. It is just kinda strange to see you adding a "in progress" label now after it is already fixed.
