### ISSUE TITLE
The long injection tests are hidden folders and photos with higher resolution

### ISSUE THREAD

**Issue by ventura16** [UnevenSoftware/LeafPic#234]
Related to the long injection tests are hidden folders and photos with higher resolution (there was a problem with the photographs taken at the nexus 5x). For example, QuickPic copes with it much better.

**Comment by dnldsht** [comment]
@ventura16 I really don't understant what you mean, can you explain it better?

**Comment by ventura16** [comment]
Oh, sorry, I think, the problem in my bad English. Okey, I try.

On my Nexus 5x I had a problem. Photos, who I do on it, loading 2-3 seconds, because they are high (4000x2992). But pictures with lower resolution is no problem. If you want, I can take the video with its problem :)

**Comment by dnldsht** [comment]
@ventura16 is delay full resolution active?
BTW I know that, I'm looking for a solution.

**Comment by ventura16** [comment]
Hm... I don't understand. Delay present in pictures with high definition

ср, 20 июл. 2016 г., 15:38 Donald Shtjefni notifications@github.com:
