### ISSUE TITLE
Fingerprint scanner security option

### ISSUE THREAD

**Issue by ventura16** [UnevenSoftware/LeafPic#235]
Whether it is possible to add an opportunity instead of a PIN code when you open the hidden folders to use a fingerprint scanner? it would be very convenient!

**Comment by TrebuhD** [comment]
I can take a crack at this if you'd like.

**Comment by dnldsht** [comment]
I haven't a phone with the finger print sensor, so if you can try do
implement it, would be great. If you have any questions about the current
method feel free to ask me.

**Comment by ventura16** [comment]
thank you, guys!

**Comment by TrebuhD** [comment]
Sure thing. I'll check it out tonight.

**Comment by ghost** [comment]
Would be also really handy the fingerprint sensor for the first access to the app, this is one of the many ideas i have wrote in the beta page on google play.
