### ISSUE TITLE
The ability to select folders to sync with cloud storage

### ISSUE THREAD

**Issue by ventura16** [UnevenSoftware/LeafPic#236]
I would like to see the folders to synchronize with popular cloud storages (For example, Google Drive, Dropbox, Yandex Drive, OneDrive), looks like QuickPic.

**Comment by wyatt8740** [comment]
This would probably get it excised from F-Droid unless the API's were totally FOSS, in which case it would merely get the 'promotes non-free network services' flag.

I'm against it, personally, but I can understand how it'd be useful. Would be great if we could use something like a FUSE filesystem to mount these "cloud" (god I hate that word) filesystems on a device.

**Comment by ventura16** [comment]
I understand, thank you! :)

**Comment by wyatt8740** [comment]
I'm not the developer, just making a comment on a possible problem with the request.
