### ISSUE TITLE
Only the first opened folder can be used properly

### ISSUE THREAD

**Issue by licaon-kter** [UnevenSoftware/LeafPic#239]
Eg.
- Open app
- Open folder "Camera"
- Wait for files
- Open picture 2, it says '2 of 24', and you can swipe to the next/previous picture
- Go back to all pics in folder view
- Go back to all folders view
- Open folder 100ANDRO
- Wait for files
- Open picture 2, it says '1 of 1' and you can't swipe
- Kill app
- Redo steps but now open 100ANDRO first
- It says '2 of 123'
- Go back to folder Camera
- Open picture 2, it says '1 of 1'

Android 6.0.1, F-Droid build 0.4

**Comment by dnldsht** [comment]
I also have noticed that issue but i can't reproduce it with that procedure.
I think I've fixed this bug with this [commit](https://github.com/HoraApps/LeafPic/commit/3d81089ed78e462c1a0794447309de2a73623b8e) are you able to build it and give me the feedback.

**Comment by licaon-kter** [comment]
Looks fixed in 0.5.2. Thanks
