### ISSUE TITLE
Picks up lots of music album art / a setting to exclude whole folders and subfolders

### ISSUE THREAD

**Issue by tech189** [UnevenSoftware/LeafPic#248]
I have a music folder full of albums and album art (100s of albums) and LeafPic picks up all of them and I would like a way to exclude the Music folder and it's subfolders please.

**Comment by rmtracey** [comment]
I'm dealing with the same issue, which can only seem to be remedied by explicitly excluding all folders under my music folder individually. It'd be nice to have a blacklist/whitelist feature which allows selecting specific folders on your phone and including/excluding subdirectories.

**Comment by licaon-kter** [comment]
After excluding (the .nomedia method) did you reboot by any chance? The thing is that the Android media server must rescan all the folders and it won't trigger right away on all ROMs.

**Comment by tech189** [comment]
I can't use the .nomedia method because then my music player would ignore my music folder...

**Comment by tech189** [comment]
A whitelist/blacklist feature with subdirectories would be nice.

**Comment by dnldsht** [comment]
I released a New version on the play store, now you can select parents of a
folder when you try to exclude one album!

**Comment by wyatt8740** [comment]
How about f-droid?

**Comment by tech189** [comment]
Thanks it works perfectly!

**Comment by brandonio21** [comment]
@tech189 If your issue is fixed (sounds like it is), can you close the issue? :)

**Comment by dnldsht** [comment]
@brandonio21 yeah! it also exclude the music directory by default.
