### ISSUE TITLE
Properly support "double tap + slide"  to zoom

### ISSUE THREAD

**Issue by DerEineDa** [UnevenSoftware/LeafPic#249]
Unfortunately, this app got the same thing wrong as most other gallery apps: Double tap + slide to zoom in and out. 

When double tapping on an image and holding the second tap, the image should not zoom in or out until I move my finger up or down. Unfortunately, it does zoom as soon as the finger touches the screen the second time, no matter if the second press just taps or holds. 

Just try it: first zoom into an image whatever way you prefer. Then try to zoom out using the douple tap + slide gesture. Unfortunately, the app already zooms in even further on the second tap, so zooming out using this gesture is almost impossible.

**Comment by wyatt8740** [comment]
I'd never thought of this at all, but it would be great, especially for users with devices that do not support multi-touch amd one-handed users.

**Comment by DerEineDa** [comment]
By the way, Google Photos is an example for a gallery that does this correctly. I think QuickPic does this correctly, too. 

Double tap + slide is a default gesture in Android since many years and is supported by most apps, like Google Chrome and Google Maps. Because I prefer to use my phone one-handed, this gesture has completely replaced "pinch to zoom" for me.

**Comment by wyatt8740** [comment]
'most apps'
(lists two google-made closed source apps that aren't in AOSP)
I'd claim most apps don't; mobile firefox ('fennec') and leafpic and Open Camera do not do this, for example. But it is a neat gesture for sure (where it works). I'd like it.
I can one-hand hold my nexus 6 and pinch zoom, though.

**Comment by DerEineDa** [comment]
The fact that many, even well known, apps don't do this correctly does in no way void my reasoning. As far as I know, the current nightlies of Firefox for Android have the "double-touch drag" gesture (as this is officially called) as well, because they replaced their own gesture detector in favor of the default android gesture detector. I'll argue that "most"  apps support this gesture because it is a default gesture supported by the Android API since KitKat. 

Even Leafpic has this gesture: The gesture itself works fine, but the premature zoom on the second touch (down, instead of waiting for release)  ruins it. 

See these links for reference:
- Explanation of the gesture: https://material.google.com/patterns/gestures.html#gestures-touch-mechanics
- Standard android API for supporting this gesture since KitKat: https://developer.android.com/reference/android/view/ScaleGestureDetector.html
- Official Support Library API to support even older android versions: https://developer.android.com/reference/android/support/v4/view/ScaleGestureDetectorCompat.html

Again, Leafpic already supports this gesture, just not correctly. So this issue is a bug report, not a feature request.

**Comment by rugk** [comment]
So as you provided sources for this gesture, I an also :+1: for implementing this. You should just follow the material design guidelines.
It does not matter how much apps do it wrong.

**Comment by wyatt8740** [comment]
@DerEineDa I'm on aurora (firefox) and see no such thing.

**Comment by rugk** [comment]
Does this mean it is fixed/implemented or what?

**Comment by dnldsht** [comment]
Just cleaning out issues

**Comment by rugk** [comment]
So this is basically a "wontfix" (without giving any reason??)?

**Comment by dnldsht** [comment]
Nope there was many duplicate issues for the zoom, I just removed them and
created a new one

**Comment by rugk** [comment]
Okay, good, which one? (That's why if you close an issue, always add a an explanation. And if you create a new one or close it as a dupe, link to that issue.) Users subscribed to this issue may want to follow the new one.
