### ISSUE TITLE
Option to disable animations

### ISSUE THREAD

**Issue by arethsu** [UnevenSoftware/LeafPic#250]
I own an older, less powerful device and would love an option to disable animations.

**Comment by wyatt8740** [comment]
I own a nexus 6 and would still like this just since it's not necessary for me.

**Comment by AmrishJhaveri** [comment]
I would like to take this up. Any document on the process to be followed? On the README there is a develop branch link but redirects me to 404.

**Comment by dnldsht** [comment]
The branch is called dev I forgot to change it in the readme.

Animations are in the recycler view, and on the view pager, so you should
look there.

**Comment by AmrishJhaveri** [comment]
Thanks. Should the animation disable option be put in Settings/General or Settings/Media Viewer? or should the animation just be removed?

**Comment by calvinnor** [comment]
@AmrishJhaveri I would have a toggle under "Advanced" settings which would disable all animations throughout the application.

Please find any other places where animations are prominent and decide upon their animators based on the toggle value.
