### ISSUE TITLE
Image zooms back out when coming out of immersive mode

### ISSUE THREAD

**Issue by coderkei** [UnevenSoftware/LeafPic#264]
when you view an image, you can tap the screen so the background goes back and goes into immersive mode, if you zoom in the image and tap again to exit immersive mode (where it shows the image name) the image zooms back out

**Comment by TrebuhD** [comment]
I've not been able to reproduce this in the latest version from the develop branch.

**Comment by coderkei** [comment]
Ah, I am using the latest google play beta, the problem occurs when I zoom
into a image and if the blue bar is visible and you zoom in, when it hides
the image zooms back out

**Comment by touzainanboku** [comment]
Happens to me as well (Play Store beta). Pretty easy to reproduce actually. Just open an image and start zooming. The moment the app auto hides the bars the image zooms back.
