### ISSUE TITLE
You can exclude excluded folders

### ISSUE THREAD

**Issue by bkp23** [UnevenSoftware/LeafPic#265]
When viewing the hidden/excluded folders, it's possible to re-exclude them. This seems to make them vanish entirely with no way to un-exclude them.
If this is intentional, please disregard.

**Comment by dnldsht** [comment]
@bkp23 are you using v0.5.2?

**Comment by bkp23** [comment]
Yes, 0.5.2. Downloaded about 12 hours ago.

**Comment by dnldsht** [comment]
so you can exclude a folder but you cant un-exclude it in the settings?

**Comment by bkp23** [comment]
My mistake. I hadn't noticed the "excluded albums" in settings. Trying this now, it looks like I've simply confused hidden and excluded folders.

This issue can be closed. Thanks for your help.
