### ISSUE TITLE
Thumbnails in folder resize (feature request)

### ISSUE THREAD

**Issue by Squinternauta** [UnevenSoftware/LeafPic#268]
I'm on a 5.7" 2k display (LG v10) and it would be nice to have the possibility to resize the image thumbnails grid. Now the grid I see is 5x7 and it's very small. Maybe a pinch to pan/zoom, or simply an option in settings menu to set a more comfortable one

**Comment by dnldsht** [comment]
Implemeted right now! you have to wait the next release.

Stay tuned!

**Comment by Squinternauta** [comment]
amazing, thanks!

**Comment by mo-504** [comment]
You can pinch to resize the thumbnails in the latest version (0.5.2), it is very difficult to control the resizing with the current implementation though.
A slider or something in settings would work better
