### ISSUE TITLE
Moving/copying pictures to SD card creates new folders

### ISSUE THREAD

**Issue by LokiBartleby** [UnevenSoftware/LeafPic#269]
When I moved or copied a picture from the internal memory to my SD card the original folder ("Bilder")  was created on the SD card, but with a strange path:
/storage/0000-0000/torage/0000-0000/Bilder
It should be /storage/0000-0000/Bilder instead. 

My phone: Samsung Galaxy S5 (SM-G900F), original 6.0.1 FW, no root. The permission to write on the SD card was given before I moved/copied the pictures.

**Comment by dnldsht** [comment]
I worked on this issue and I think I get it fixed (I tested it only on a device with Lollipop), are you able to build the develop branch and give me a feedback? otherwise here are an [apk](https://drive.google.com/file/d/0B4G2W-xokbBrTFF0ODVNZlE5LXM/view?usp=sharing).

**Comment by MarcRdC** [comment]
Tested this build (v0.5.4) on Android 6.0.1; can copy but not move: asks for writing permission — already granted — when picture is selected from column view and does nothing when image is open. (Also: copy and delete operations seem a bit long.)

**Comment by dnldsht** [comment]
This time should work also move, can you test it again?
the only thing that doesn't work is to copy it on the same folder!
apk [here](https://drive.google.com/open?id=0B4G2W-xokbBrTVFtNmhCWlluYUk)

**Comment by MarcRdC** [comment]
Yes, it is working! ;-) But still taking some time to complete.

**Comment by dnldsht** [comment]
I'm closing this since it is related to #201
