### ISSUE TITLE
3gp Videos not detected

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#271]
When i took a video of low quality that was of 3gp format, i went into LeafPic to find the video but it wasnt there. When i used another app such as F-Stop to view it, it was there.
Seems like LeafPic doesnt detect all video formats.  Can this be fixed?

**Comment by zeddysoft** [comment]
Surprisingly, i downloaded a 3gp video and it showed up on LeafPic, anyone with the same issue or has the issue been fixed?

**Comment by zeddysoft** [comment]
@dnldsht can you confirm this from your end?
