### ISSUE TITLE
[Request] Update F-Droid

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#276]
Recently installed 4.0 on F-Droid not realizing it was outdated.

**Comment by dnldsht** [comment]
It will be availabe in these days, but it would have a different package name after the story of the russian guy (I had to change it when I relased leafpic on the playstore). I'mgonna update the link int the readme when it will be availabe.

**Comment by rugk** [comment]
Where can we hear more about this "story"? 😊

**Comment by ghost** [comment]
@dnldsht Well, you should redirect F-droid users to here at the very least.

**Comment by dnldsht** [comment]
here is the [link](https://f-droid.org/repository/browse/?fdfilter=leafpic&fdid=org.horaapps.leafpic) of the updated version on F-droid. the old version would be removed after a while, I'm gonna told them to flag the old version as OUTDATED.

@rugk you can find more information on this [post](https://www.reddit.com/r/Android/comments/4wvhsn/dev_leafpic_gallery_now_in_beta_on_playstore/).

> Does anyone remember this thread? I want let you know that another guy release an older version of the app on the playstore, he doesn't follow the terms of the GPL v3 license, since he didn't release the source code and removed all informations about our team. I tried to talked him, but he answer me only with russian insults! He may have change the code adding some kind of spyware so be carefull and don't install it. He also said that he is never gonna release the source code! here you can find the app released by the other guy. I tried to contact google again but they don't answer. I hope you guys report it to google. (I'm not against that other people release a version of this project but they have to follow the terms of the license). 

Now the "fake" app isn't available anymore since a lot of people flag it as inappropriate and give it bad reviews

PS I'm also gonna update the badge of the f-droid on the README.md

**Comment by licaon-kter** [comment]
O RLY? See **ehartwell** comments and my response: http://www.xda-developers.com/xda-external-link/leafpic-an-open-source-material-design-gallery-alternative/

My first comments conclusion was sadly made true? :-(

**Comment by dnldsht** [comment]
@licaon-kter the app was released twice before the official launch on Play Store! So I decided to release it on a beta version to avoid that someone else release it without follow the terms of the license.  

The first one also make a pull request but after a few minutes he reverted it but at least he changed the package name before relase it the second one just removed the donate and about activity.

**Comment by dnldsht** [comment]
old application removed from F-Droid

**Comment by rugk** [comment]
So where is the new one? Does it have a different name?

**Comment by dnldsht** [comment]
@rugk it hase the same name with a different package name (org.horaaps.leafpic)

and here it is the new one https://f-droid.org/repository/browse/?fdfilter=leafpic&fdid=org.horaapps.leafpic
