### ISSUE TITLE
[Suggestion] Hide Pictures individually instead of Folders

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#277]
I often want to simply hide pictures instead of folders completely.

**Comment by brandonio21** [comment]
Working on it now.

**Comment by ghost** [comment]
@brandonio21 Awesome!

**Comment by brandonio21** [comment]
@dnldsht Can we close this? Or would you rather close issues when they're merged from `develop` into `master`?

**Comment by dnldsht** [comment]
@brandonio21 we have to close this manualy since noone made a commit to close it automaticaly, but really soon i should release a new version and merge stuff on master branch, in this way also f-droid can build the new version.
