### ISSUE TITLE
[Improvement] Hiding feature

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#283]
The current way makes it that all my pictures in x folder wouldn't appear anywhere but if x folder gets new pictures while x folder is hidden then those new pictures seem to never show up, could the folder still exist but the pictures inside are each hidden instead of the whole folder and new pictures are automatically hidden if any new picture is created in x folder?

**Comment by ghost** [comment]
Sorry, close this issue. This is already the case.

**Comment by dnldsht** [comment]
Ok
