### ISSUE TITLE
[BUG] Exclude button crashes LeafPic each time.

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#284]
The exclude button always makes the app crash and I'm unsure as to why.

**Comment by Valeria-AT** [comment]
https://github.com/HoraApps/LeafPic/issues/272 ?

**Comment by ghost** [comment]
@Theobald93 can confirm it does the same for me.

**Comment by dnldsht** [comment]
duplicate of #272 and fixed in the dev branch!
