### ISSUE TITLE
[Proposal] A Proposal to Clean Up the LeafPic Data Layer

### ISSUE THREAD

**Issue by brandonio21** [UnevenSoftware/LeafPic#286]
## Problem

Currently, the LeafPic project is a bit of a mess. Judging by the way the code is arranged, it is suffering a pretty large amount of tech-debt due to rapid featuring. This is a problem in all projects. However, I believe it is hindering LeafPic's growth. The code is hard to grok and layering is almost non-existent. 
## Scope

I propose that to combat this, the "data layer" of LeafPic be cleaned up. Currently, The `Album` and `Media` classes have a ton of responsibilities and are used quite frequently. As a quick example, an Album keeps track of what media items are selected within it. This is a huge violation of [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle) as it is not only managing its own data but also the data of the UI layer as well.
## Proposed Changes
1. Clean up the _Album_ class to only manage its own data
2. Clean up the _Media_ class to only manage its own data
3. Eliminate the homegrown SQLite solution we have and attempt to leverage a third-party ORM (eg [sugar](https://github.com/satyan/sugar))
4. Increase performance by designing well
5. Allow the UI layer to keep track of its own selections
## Principles

During the implementation of the proposal, [Clean Code](https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882) principles will be followed. The following rules shall be followed:
1. Functions will do one thing and one thing only
2. Functions should be no more than 10 lines
3. Naming will be intentional and precise

I plan on getting started with this tomorrow. I believe that the current state of the codebase is really preventing accessibility. Please comment if you have any suggestions.

**Comment by dnldsht** [comment]
I'm a begginer developer so I'm happy to see new ways to work, I tried to get the Data layer away from other ones but it wasn't easy.
I have a question about this point:

> 1. Eliminate the homegrown SQLite solution we have and attempt to leverage a third-party ORM (eg sugar)

are you plannig to save more stuff on the database?

**Comment by brandonio21** [comment]
@dnldsht Thanks for your enthusiasm! This change shouldn't add/subtract the amount of information stored on the database. It probably will change the schema, however.

**Comment by wyatt8740** [comment]
> Functions should be no more than 10 lines

Don't speak in absolutes like this. A function that does one thing and takes more than 10 lines is possible. This is Java, not a religion.

> Increase performance by designing well

That's extremely vague.

(also, following the 'object oriented' principle too far is very easy to do; don't worry too much about SRP beyond what needs to happen to improve readability and usability. Disclaimer: I am a C programmer first and foremost. OOP seems overly-applied in a lot of cases on 'religious' grounds to me.)

That's my two cents. The rest of this looks like a pretty good idea.

**Comment by brandonio21** [comment]
@wyatt8740 Thanks for your comments. Maybe I was indeed being _too_ absolute in my original proposal. In fact, while refactoring, I have indeed created some functions that are more than 10 lines. The point instead being that functions should be kept _small_.

This is quite the task.. I've gotten started, but it will take some time. I truly believe that the added extensibility and readability will be worth the effort, however.

**Comment by wyatt8740** [comment]
uh, @brandonio21 did you hit 'comment and close' by mistake?
I agree that cleaning code is a good thing.

**Comment by brandonio21** [comment]
@wyatt8740 After working on refactoring the data layer for about 6 hours, I was becoming increasingly frustrated at the intermingledness of everything. I felt as though I was not making any discernible progress. 

Therefore, I have decided to abandon this (short-lived) LeafPic refactoring attempt.

**Comment by wyatt8740** [comment]
@brandonio21 This is what happens when a programming language tries to force 'object orientation' of everything. If a non-OOP programmer tries to use it, Java becomes a perversion of C, unfortunately :\

Anyway, A for effort.

**Comment by dnldsht** [comment]
@brandonio21 I want to clean most part of the project by myself, can you give me any advice on how can I split the data layer from the UI layer, for example the selected on album and  on media class.

**Comment by brandonio21** [comment]
I think the biggest ways that things can be cleaned up is by more strictly following the [IS-A/HAS-A ](http://stackoverflow.com/questions/2218937/has-a-is-a-terminology-in-object-oriented-language) methodology. Then, you can separate the classes into their various chunks. Once this is done, you'll find that things fall nicely into the [open/close principle](https://en.wikipedia.org/wiki/Open/closed_principle), which will make it easier to accomplish seemingly large issues like https://github.com/HoraApps/LeafPic/issues/288 much easier.

We assert the following as true:
- **Albums** and **Media** both have preview images (cover images, thumbnails)
- **Albums** and **Media** both exist on a filesystem (right now is is limited to the local Android FileStore.. but in the future maybe you'd like to support cloud?)
- Each type of **Media** is viewed differently (GIFS vs Photos vs Videos)

We also know the following:
- An **Album** HAS-A Cover Image and CONTAINS Media
- The _rename_, _move_, and _delete_ operations of **Album**s and **Media** are specific to the filesystem that they reside on. (If you choose to support cloud storage, for instance, deleting an album from cloud storage would be different than deleting an album on the local android machine).

Therefore, the following design could be imagined:

```
+ interface Filestore
|--- getAlbums() -> List<Album>
|--- deleteItem(FileStoreItem item)
|--- renameItem(FileStoreItem item, String newName)
|--- moveItem(FileStoreItem item, Album newParent)

+ class FileStoreItem
|--- getFileStore() -> FileStore
|--- getPreviewImage() -> Bitmap
|--- rename(String newName) => getFileStore().renameItem(this, newName)
|--- move(Album newParent) => getFileStore().moveItem(this, newParent)

+ interface GridDisplayable
|--- Activity getClickActivity()

+ class Album extends FileStoreItem implements GridDisplayable
|--- private Bitmap coverImage
|--- List<Media> contents
|--- getClickActivity() => // show album contents
|--- override getPreviewImage() => {
             if (coverImage) return coverImage
             else return contents.size() > 0 ? contents.iterator().next().getPreviewImage() : null
       }

+ class MediaType
|--- Bitmap getPreview()
|--- Activity getViewMediaActivity()

+ class Media extends FileStoreItem implements GridDisplayable
|--- private MediaType mediaType
|--- Activity getClickActivity() => mediaType.getViewMediaActivity()
|--- override getPreviewImage() => this.mediaType.getPreview()
```

This design allows for easily adding new media types, new filestore systems, etc. In order to interleave this with the UI layer, the UI just needs to have a _List<GridDisplayable>_. The UI will also keep track of which _GridDisplayable_ objects are selected, etc.

As a disclaimer, this is just my opinion. Nothing about this is 100% correct and I am a relatively-new Android developer so some of the information may be misleading (I believe `Activity getViewMediaActivity()` is misleading because returning an Activity is weird).

But I think this is a good way to organize things to allow for extensibility.

**Comment by wyatt8740** [comment]
I'm not a fan of 'accessors' and the like in OOP, but if that's cleaner in your eyes, it would be a good change.
