### ISSUE TITLE
Full size images not loading with version 0.5.2

### ISSUE THREAD

**Issue by dorkster** [UnevenSoftware/LeafPic#289]
In version 0.4, zoomed images appeared clear if I disabled the "Delay load full-size image" option. That option is missing in 0.5.2, and it appears that full-size images are never loaded. I'll provide some screenshots to better illustrate the issue here:

**v0.4**

![leafpic_0 4](https://cloud.githubusercontent.com/assets/913982/17652811/bb7459e6-6254-11e6-8725-81a1d37beb4e.png)

**v0.5.2**

![leafpic_0 5 2](https://cloud.githubusercontent.com/assets/913982/17652814/c7d35aca-6254-11e6-963f-129f78c5b7ec.png)

**Comment by wyatt8740** [comment]
I was trying to get an option kept to disable the 'previewing' behavior entirely. Hope this gets fixed soon.

**Comment by alekksander** [comment]
confirmed
