### ISSUE TITLE
[Request] Support API16

### ISSUE THREAD

**Issue by kinclma1** [UnevenSoftware/LeafPic#291]
Hello, is it possible to support API16 (Android 4.1) even if it wouldn't include some features?

**Comment by wyatt8740** [comment]
I support any and all backward compatibility efforts, but am unsure how much would need to be altered to support API 16 since I don't have a SDK installation handy.

I'm on 5.0.1, so I'm okay, but I always try to support as old of OSes as I possibly can with software I write.

**Comment by kinclma1** [comment]
The app builds on 4.1, but doesn't start complaining about many system classes.

**Comment by dnldsht** [comment]
@kinclma1 I'm sorry but we support api 19+, and we dont have any plan to support lower versions.

**Comment by kinclma1** [comment]
Alright, thanks.
