### ISSUE TITLE
Resolution no showing up

### ISSUE THREAD

**Issue by alvinRT** [UnevenSoftware/LeafPic#296]
When I go to see the details of a photo taken with Open Camera app, the resolution is showing "0x0". But when I check the details of that same photo with my native gallery app, it shows the resolution properly. This doesn't happen when the photo is taken using other camera app, such as Cameringo+. I hope this is fixed soon. I'm loving the app. Thanks in advance.

**Comment by alvinRT** [comment]
Forgot to mention that my phone is Axioo Picophone L1 running Android 5.1

**Comment by pstarek** [comment]
@alvinRT I have LeafPic 0.5.2 installed and Open Camera 1.32.1 installed on my Vibe P1m and resolution of pics from Open Camera app (and from stock Lenovo camera app) is shown in LeafPic correctly. Do you have installed latest versions of apps?

![screenshot_2016-08-23-11-21-55](https://cloud.githubusercontent.com/assets/1451061/17886928/5d61e482-6924-11e6-98ad-2d2020cebd81.png)

**Comment by licaon-kter** [comment]
@alvinRT You need to uninstall 0.4.4 and reinstall version 0.5.2.
