### ISSUE TITLE
Moving Pics to SD Card Doesnt fully work

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#298]
So i have the latest version of LeafPic.

When i select ALL photos, or maybe even 2 or 3, to move them from internal memory to SD Card folder - Firstly takes forever to happen because that circle keeps spinning for more than a minute!!  And secondly as i said selecting all photos or selecting more than one photo, after it takes forever will move only **the first pic that was selected**!!  I dont understand why this is happening, is it a bug or something??

**Comment by dnldsht** [comment]
I'm closing this since it is related to #201
