### ISSUE TITLE
[Feature Request] Improve security

### ISSUE THREAD

**Issue by AboShanab** [UnevenSoftware/LeafPic#299]
Hello, I Just see that's nice application and i completely use it but it lose some feature at security like :- 
- Ability to make a hard password not only numbers ( I mean numbers and letters, characters )
- Ability to use the fingerprint as password.
- Add an option to lock this application at all ( I mean you can't join application to see media without enter the password ).
-  Make the hidden media encrypted that's make it more secure ( for android 6.0 and lower because at android 7.0 the encryption will work at files ).

Other ideas are welcome, Thanks for reading.
Best regards,
AboShanab.

**Comment by dnldsht** [comment]
Right now on holiday but when I come back I will look at this features and
to android 7!
Cheers!

**Comment by AboShanab** [comment]
@dnldsht Okey, take your time.

**Comment by wyatt8740** [comment]
Does this mean encrypting files? or requiring a password to start an app? or mounting encrypted partitions?

**Comment by AboShanab** [comment]
@wyatt8740 
- Does this mean encrypting files?
  I mean Encrypting the files which use hide feature in this app.
- requiring a password to start an app?
  I mean requiring a password to start this gallery app not other app, this feature work when setting an password and select this option.
- mounting encrypted partitions?
  I don't say any mounting in this request.

**Comment by chesio** [comment]
> I mean Encrypting the files which use hide feature in this app.

Please, no. This is so out of the scope of image gallery app.

Besides, @AboShanab would you trust an app that has [issues](https://github.com/HoraApps/LeafPic/issues/201) with moving/copying files around to encrypt your data? I don't want to sound offensive, LeafPic is a great app, but encryption is hard to implement properly and there are issues that are much more urgent (and in the scope of the app).

**Comment by AboShanab** [comment]
@chesio This application is open-source, so anyone can request his ideas to make the application better, issues will take the high priority.

**Comment by chesio** [comment]
> This application is open-source, so anyone can request his ideas to make the application better, issues will take the high priority.

I'm not questioning that, that's completely right, but in the same way anyone can express his disapproval.

> Would you trust an app that has issues with moving/copying files around to encrypt your data?

So, would you? ;)

**Comment by AboShanab** [comment]
@chesio : lol no, but this is an ideas for future.

**Comment by dnldsht** [comment]
@chesio @AboShanab encryption has a very low priority i will make LeafPic solid before add a feature like that (and it will not be related with hidden folders). 

> Would you trust an app that has issues with moving/copying files around to encrypt your data?

Google doens't care about developers and make their life hard, I'dont know if you are a developer but I have to handle in a very different way operations on files if they are on an external memory. 

BTW copy & move works also on SD now on the dev branch I only have to improve it.

**Comment by chesio** [comment]
@dnldsht This was not meant to be disrespectful to you or other app devs in any way, I was just trying to make my argument pragmatic. Getting encryption right is hard. Getting encryption right on Android is perhaps even harder when you say you have to handle external memory in a very different way.

I appreciate your work, LeafPic is my only gallery app in the moment. It's lightweight, it's simple, I love it. I'm not sure it would stay this way with file encryption baked in, so I dared to chime in.

**Comment by wyatt8740** [comment]
@dnldsht Sorry to hear that Google works like that (though my experiences with JNI already made me suspicious of this). At least there's no $100/year recurring fee just to sign your apps for sideloading though.

**Comment by manuelpaulo** [comment]
Encryption would be great. I see no point on the 'hidden folders' feature since any browser will be able to find the images/movies.  (dot .files & .nomedia)

I've hide a movie on a 'hidden' folder and VLC found it easily, or am I missing something?

Also, why not simply use the Internal Storage (MODE_PRIVATE) to hide files?
