### ISSUE TITLE
preserve timestamp on copy

### ISSUE THREAD

**Issue by mnalis** [UnevenSoftware/LeafPic#300]
When image is copied (or move, but haven't used that yet) its original timestamp should be preserved. Currently (f-droid leafpic 0.5.2) date/time of the copied file it is set to current time (which messes up sorting, and "fix date" option also doesn't work for me)

**Comment by licaon-kter** [comment]
Android bug, afaik, you can't set date&time for files since Android 3.0.

/close as wontfix
