### ISSUE TITLE
"fix date" doesn't work for me

### ISSUE THREAD

**Issue by mnalis** [UnevenSoftware/LeafPic#301]
Says "unable to fix date".

See http://i66.tinypic.com/jjuu6h.jpg - image resized by tinypic site, but exif seems to be preserved verbatim.

On Debian GNU/ linux using exif package says it it " 2016:03:25 22:52:59" so original timestamp is in there.

Leafpic 0.5.2 from f-droid. Original picture was taken on samsung galaxy S2 on cyanogenmod9.

**Comment by dnldsht** [comment]
I forgot to add a warning this feature doesn't work on all devices and with all images, it is an Android problem.
