### ISSUE TITLE
supporting lower API versions

### ISSUE THREAD

**Issue by navidei** [UnevenSoftware/LeafPic#302]
Hi,

I want to know which features aren't available for API versions below 19? Is this considered due to libraries or because of features that leafPic has itself?

As mentioned in [Google's official documentations](https://developer.android.com/about/dashboards/index.html) right now leafPic is missing something about 17% of potential users.

Thanks.

**Comment by navidei** [comment]
Is there any details about this one that you can inform me about? I need to add this library to my project which is using a minsdkversion of 17. I want to know which parts are not available below 19 that I could remove them from project; Or if they are necessary in the project I refactor them to support API 17.

Thanks.

**Comment by navidei** [comment]
If you could mention the parts that are not supported in lower API versions maybe I could help to make this great library available for older devices.

**Comment by dnldsht** [comment]
@navidei I don't own any device that runs lower versions of android, I don't even know which parts of the project don't work, so if you wanna test it you have to set the min SDK to API 17 and find where it doesn't work.

**Comment by navidei** [comment]
Yes @dnldsht  I'm testing it now on an emulator. I think the parts related to accessing files in SD card are the bottlenecks. I'm working on it.

**Comment by dnldsht** [comment]
@navidei the sd card is messed up also on the latests versions, I found a workaround for API 21+, but I'm still looking for a better way to handle it. 

If you find something please let me know! Cheers!

**Comment by wyatt8740** [comment]
@dnldsht If your computer is powerful enough, you could always emulate android 4.x in qemu.

I did it when porting C programs to android before I even owned a real android device to test on (I now use a Nexus 6).

**Comment by navidei** [comment]
@dnldsht I think I have fixed some lines to support lower API versions at least until API level 15. I was working on version 0.4 at least from a month ago and I haven't pulled the changes since then, so the workaround around this may not be applicable to the recent versions. I attached a file were changes are listed related to version 0.4, you can check [this file.](https://github.com/HoraApps/LeafPic/files/545824/changes-for-pre-Kitkat.docx)
