### ISSUE TITLE
Implement Android's new "share menu" (grid instead of list)

### ISSUE THREAD

**Issue by armandojrod** [UnevenSoftware/LeafPic#309]
This (new share intent, GRID)

![This (new share intent, GRID)](https://cloud.githubusercontent.com/assets/10835960/18060454/616a002e-6dec-11e6-89be-2a6024167d70.png)

VS

This (old share menu, LIST)

![This (old share menu, LIST)](https://cloud.githubusercontent.com/assets/10835960/18060488/83564e54-6dec-11e6-9d08-8aa2335d901b.png)

**Comment by TrebuhD** [comment]
Was this introduced in Android 7.0? Are you sure this isn't some sort of a custom view?

**Comment by armandojrod** [comment]
I'm pretty sure its the default Marshmallow share dialog, the one with Direct Share on top, most Google apps use it.

https://developer.android.com/about/versions/marshmallow/android-6.0.html#direct-share

https://www.bignerdranch.com/blog/implementing-android-marshmallow-direct-share/

**Comment by dnldsht** [comment]
this thing is available since 6.0, just forgot to add it to multiple share. 
now is implemented, new release soon!
