### ISSUE TITLE
Option in manipulation tools to write to new file

### ISSUE THREAD

**Issue by giwu37** [UnevenSoftware/LeafPic#315]
Hi all,
When manipulating files like crop, resize etc. it would be a nice option to select "write to new file".
Could be a LeafPic-Save-Folder or adding _leafpic to the filename.
TIA!
Greetings
Sebastian

**Comment by touzainanboku** [comment]
Adding a number to the original file name would also work.

**Comment by dnldsht** [comment]
v0.5.9 create new file, in the next one I'm gonna ask if overwrite the file or save a new one.
