### ISSUE TITLE
Wrong Folder Selection when "Auto Update Media = off" and "Sort=Date"

### ISSUE THREAD

**Issue by Valeria-AT** [UnevenSoftware/LeafPic#316]
Hey, sometimes when i copy/create pictures in a folder that is "old" (not in the left upper corner) e.g "Folder A" then go back to the main grid view and then select the left upper folder "Folder B" it opens "Folder A" because the grid is wrong because of this combination.

Not good reproduceable.
Leafpic 0.5.2

**Comment by dnldsht** [comment]
may this be related with #342 ?

**Comment by Valeria-AT** [comment]
Could be, both describe that the shown indexes (of folders/pictures) are not the same like the real indexes.
But i do not think you can fix it easily with a simple change, my issue is a sideeffect of no-auto-update.

In #342 the new order is shown and the program uses the old order.
In my issue the old order is shown (because no auto-update) and the program uses the new order.

My issue should be also occur in the other sorting orders too, every time the order changes because of file deletion/creation/moving.

**Comment by dnldsht** [comment]
@Theobald93 It can't be related with 'Auto Update setting', last night changed some stuff and now indexes are handled correcly. I'm gonna release a version so you can test it!

**Comment by Valeria-AT** [comment]
@Leafpic 0.5.9
After ~20 testings I had no error with the folder selection. Good job!
I will reopen the issue if I will get some in the future.

Or didn't you release a fix yet and i just had luck with all the tests?^^
