### ISSUE TITLE
Black screen shown instead of image

### ISSUE THREAD

**Issue by tp0** [UnevenSoftware/LeafPic#317]
This is somewhat hard to preproduce, but basically some photos just do not load. Instead, a black screen is shown:

![screenshot_20160907-014014](https://cloud.githubusercontent.com/assets/5863551/18293916/66c3a49a-749e-11e6-9a93-af64106cb631.png)
- When first time loading it, it looks like the image very briefly flashes before the black screen.
- The thumbnail of this image always shows up in the folder view.
- Same thing if the image is opened directly via a file manager (Leafpic set as the default app).
- **After moving or copying the image to another location or renaming it shows up again**, but after this other pics in the folder then start to have this same problem. It seems to be very random.

I couldn't reproduce this with the _same_ pics reliably enough, but so don't think an example file would be useful and without sharing the whole folder.

Culprit doesn't seem to be:
- size of the image
- file name (all files named the same way with numbering)
- EXIF
- hidden/excluded folder status
- internal storage vs. SD card
- amount of pics in the folder

v0.5.2 (tested on Play and F-Droid version)
Default settings other than theme.
Marshmallow 6.0

**Comment by transplier** [comment]
This happens around 95% for me on my lg g3 running cm13, but only on pics i took at 13mp. Opening the image by tapping on the gallery thumbnail always works, but any of these actions trigger the issue more often than not :

1. Swiping to change image. 
2. Tapping on image to go full screen. 
3. Pinch zoom. 
4. Changing device orientation. 

Once triggered, the issue persists until I go back to gallery view. Interaction still works (ie if i swipe the title bar updates). 

Pics taken at 8mp or lower don't seem to exhibit the issue. Video memory?

**Comment by transplier** [comment]
The subscaling mode seems to work around the issue.
