### ISSUE TITLE
MediaPagerAdapter image sort order seems to be broken 

### ISSUE THREAD

**Issue by pelya** [UnevenSoftware/LeafPic#320]
Open album with 20 images, open first image, then swipe left. On my debug build of 'develop' branch, without any extra commits, this shows the same image three times, then shows other images in incorrect order.

**Comment by dnldsht** [comment]
@pelya how are you trying to sort them?

> this shows the same image three times

does it persist with only on album? have you tried to use the alternative media provider in the settings?
do you show them in them in the correct order on the main activity?

**Comment by pelya** [comment]
Any sorting order gives the same result, I've tried name sort, date sort
and size sort.

The bug is very visible and happens immediately on any album, so if you're
not seeing this, it's probably some error in my build environment.

I'll wait for the official release to confirm, please close this issue,
chances it's just a false alarm.

**Comment by dnldsht** [comment]
@peyla you were right i borke it with the last commit, fixed now!
