### ISSUE TITLE
Error in Setting Video

### ISSUE THREAD

**Issue by harshmittal2810** [UnevenSoftware/LeafPic#331]
When i check uncheck video inbuild button
It crashes
please find the bug and inform me.
Nyc App and nyc coding

Thank you

**Comment by jerryn70** [comment]
After enabling use inbuilt video player, when I click any video to play app shows unfortunate stopped/closed error

**Comment by dnldsht** [comment]
@mittalharsh2810 @jerryn70  are you using the v0.6-beta-1?

**Comment by harshmittal2810** [comment]
No i am using v0.4

**Comment by dnldsht** [comment]
@mittalharsh2810 you can find new releases [here](https://github.com/HoraApps/LeafPic/releases)

**Comment by jerryn70** [comment]
I'm on the latest version
