### ISSUE TITLE
can not edit pictures

### ISSUE THREAD

**Issue by heinzbloed** [UnevenSoftware/LeafPic#332]
hi, thanks for developing open source software!

i can not edit photos, btw. can not save those changes.
i can see the changes, but if i come back to the gallery, the changes were lost/undo.

i got a special setup with omnirom 6.0.1 on a galaxy nexus without any google stuff.
maybe this is a problem (missing libs?)

i got a log with logcat while editing files, maybe you got an idea where i can search for solutions.
Thanks.

[logcat_leafpic_edit_picture.txt](https://github.com/HoraApps/LeafPic/files/491600/logcat_leafpic_edit_picture.txt)

**Comment by dnldsht** [comment]
@heinzbloed with the new release when you edit an image it create a new file with the changes.

**Comment by touzainanboku** [comment]
@dnldsht have you pushed the new update to the Play Store?

**Comment by dnldsht** [comment]
@touzainanboku not yet, I'm figuring out some problems with donations via in app-purchase.
[here](https://drive.google.com/open?id=0B4G2W-xokbBrMUVYa3UtLUkwRVk) is the link of the new version

EDIT: pushed on the playstore the new release, f-droid will take it automaticaly

**Comment by touzainanboku** [comment]
@dnldsht thanks for the DL link! And I wish you luck in fixing those issues.

**Comment by heinzbloed** [comment]
thanks for your investigstion.
i'm only using f-droid so theres is the question who push the new version to f-droid...?
on previous test it seems that leafepic can copy files but can not rename files.
maybe this is a problem of masrshmallow aka aosp 6.X
i will donate your project, thanks!

**Comment by rugk** [comment]
I also experience this error. Is the build already on FDroid? If so, which version?

**Comment by heinzbloed** [comment]
the new Version is now in F-Droid, for me it works.
thx

**Comment by Bugsbane** [comment]
@dnldsht Are you aware of Google's"lovely" change in terms of services recently that ban donation links in apps unless they're using Google's in-app payment services (netting them 30% of your donation)?

Most other devs are doing separate versions for Google Play now without the donation links (or accepting that 30% goes to Google( and leaving them in, in Fdroid et al.

Don't be evil, my butt. :(

**Comment by dnldsht** [comment]
Thank you for warn me, I'm gonna read these terms and make some changes to
the donations.

BTW for every donation Google doesn't take 30% it get more: they took 30%
for every purchase and you have also to pay the vat and it depends from the
country.  If somebody donate me 2€(2.39€) I receive something like 1.40€

**Comment by rugk** [comment]
I think the current edit model is still not good. It only shows me a message that a new fully was created, but I cannot see the file right away. Instead I have to go or of the folder and go into it again.

This is still very bass UX. Please just show the edited file directly after saving the changes.

**Comment by rugk** [comment]
Does this mean it is fixed/implemented or what?

**Comment by dnldsht** [comment]
This i s fixed in dev branch
