### ISSUE TITLE
Bicubic for detailed/clean pixel view

### ISSUE THREAD

**Issue by v-cycl3** [UnevenSoftware/LeafPic#334]
Hey would be truly useful some people use bicubic editing each pixel without blurred style.

I also know Chrome is best used to view pixel art images than Firefox for that difference

**Comment by Bugsbane** [comment]
This is pretty subjective as to what is "better". If you want to edit retro pixel-art graphics zoomed way in then no bicubic filtering is definitely better, however for most people viewing photographs zoomed out, the aliasing provides a more naturalistic view that more closely resembles the original image.

**Comment by wyatt8740** [comment]
If the library currently being used doesn't let you specify how you want to scale, and you aren't opposed to using native code, swscale from ffmpeg is a fantastic library for this kind of thing. Just a thought in terms of how it could be implemented.
