### ISSUE TITLE
Cropper Issues

### ISSUE THREAD

**Issue by berrysoda** [UnevenSoftware/LeafPic#336]
If you pull the crop box past the area of an image, it recenters the crop box.
Using the 1:1 aspect ratio setting for the crop box doesn't actually lock it to 1:1

Video of this: https://youtu.be/nUVtSY_ayNY

Note: trying to play that video file video in Leafpic causes the app to auto crash

Personal
Only being able to crop by pulling from the corners of the crop box causes the crop to easily get messed up. I feel it'd be best if you could pull from the sides as well. Quickpic probably had the most efficient cropper I've used, as an example.

**Comment by dnldsht** [comment]
Right now the editor is an external library, mostly because I had other stuff to do on this project,  but now I'd like to make a new one from the scratch that allow you you to crop easly and add some features like mirror and draw.

**Comment by dnldsht** [comment]
related to #177
