### ISSUE TITLE
[Bug] Subfolders of hidden folders are not shown

### ISSUE THREAD

**Issue by razorsoup** [UnevenSoftware/LeafPic#348]
When viewing hidden folders, any subfolder of a hidden folder that doesn't have a .nomedia file in it is not displayed. Only the parent folder is displayed. This means that any such folders are excluded from both views. Ideally they should be displayed as hidden folders.

**Comment by dnldsht** [comment]
if you enable the 'Alternative Provider' would they appear?

**Comment by razorsoup** [comment]
No, that doesn't seem to work.

**Comment by WolfgangAndreas** [comment]
Having the same problem here. Alternate provider does not help.

**Comment by zeddysoft** [comment]
@razorsoup i think the issue has been fixed, tried recreating the issue here by creating an hidden subfolder in a hidden folder with **no** .nomedia file in the subfolder and the subfolder is displayed by LeafPic

**Comment by zeddysoft** [comment]
@dnldsht have you confirmed this from your end?
