### ISSUE TITLE
About screen connects to Google

### ISSUE THREAD

**Issue by rugk** [UnevenSoftware/LeafPic#351]
When accessing the about screen the app tries to connect to Google.

Please remove this as it is unexpected and it might be a privacy problem.

**Comment by wyatt8740** [comment]
You talking about the links to their google+ profiles?

If you make the connection without cookies, I fail to see any non-tinfoil-hat problems, but then again what do I know?

I just think this is kind of silly.

**Comment by rugk** [comment]
> I just think this is kind of silly.

Yes, i think so too. It is silly to connect to Google there. I mean it is not needed as far as I see, so there is no need to connect to any third-party service.

**Comment by wyatt8740** [comment]
@rugk I meant it's silly to be this paranoid.
You're not wrong about it not needing to connect, and I'd probably just store the developer images in the app itself, but it's still silly to be really worried about it when you realize how much tracking goes on just from using websites normally.

**Comment by rugk** [comment]
Still this is your personal opinion. There may be users, who are more concerned about this.

In your browser users can greatly control this stuff with various add-ons and so on. In apps, however they usually won't notice such a thing at all - not to talk about preventing it.

So even if you think there's nothing wrong with that, I'd suggest you to change it for those who may be that paranoid. It is unexpected by users and in floss apps (which could get sneaky red warnings on FDroid) this really should not happen.

Therefore please change it. As it seems there are no disadvantages when including all stuff in the app.
However there are other advantages:
- works offline
- is always fast, does not depend on network speed
- no loading time, user sees result directly

**Comment by wyatt8740** [comment]
@rugk I agree it will probably cause a 'promotes non-free network services' tag. I agree with everything you said except loading time, since the rest of the about page displays even when offline.

**Comment by dnldsht** [comment]
@rugk In the about page it try to connect google when it have to show team members profile image, I'm gonna reduce their resolution and add them in the drawable folder. I'm also gonna clean the f-droid version removing all the non-free network access like google maps and images from google+.

**Comment by rugk** [comment]
So it is fixed?

**Comment by dnldsht** [comment]
Will move images somewhere else

**Comment by dnldsht** [comment]
pictures now are stored inside tha app
