### ISSUE TITLE
ever check memory leak?

### ISSUE THREAD

**Issue by chgmxx** [UnevenSoftware/LeafPic#352]
We I using this app, I found that the memory increase up to 500M for usage.

**Comment by Valeria-AT** [comment]
Garbage collection is working on my phone. The app ram usage increase to max 250mb and then it will be reduced to ~200mb.
Xiaomi Redmi 3 with 2GB RAM.

**Comment by dnldsht** [comment]
@chgmxx may I know what device do you own? cause the ram usage isn't so high on device I tested and no one complained about that.
