### ISSUE TITLE
[Feature Request] All type Video Format Support (like; MX Player)

### ISSUE THREAD

**Issue by jerryn70** [UnevenSoftware/LeafPic#354]
The problem with every gallery app is that non of them supports all video formats, we have lot of videos with different formats and when we look at the gallery it shows only few videos, and we need to go to other video player apps to watch others. 

It will be great if you add all video support to this gallery like mx player .
 Mx video player supports all type of videos with seperate code app. So i think you can also make things like that to make this gallery fully featured .

**Comment by dnldsht** [comment]
The video player is based on [ExoPLayer](https://github.com/google/ExoPlayer) so LeaPic supports only the formats that ExoPlayer supports
