### ISSUE TITLE
Rather a request than a problem

### ISSUE THREAD

**Issue by Kratsac** [UnevenSoftware/LeafPic#355]
Is it possible to add a gallery including all pictures from all existing folders? Here, I would prefer to see them ordered chronologically. Thanks!

**Comment by marmeladema** [comment]
If i understand correctly, i think i have a similar use case.

I use Nextcloud to synchronize my photos and they are automatically moved from:
* `<gallery>`

to:
* `Nextcloud/<gallery>/<year>/<month>`

and i have multiple galleries:
* Camera
* Screenshots
* Download
* etc

Then problem is that LeafPic shows me galleries called 01, 02 and so on.
It has two majors drawbacks:
* New galleries are created every month for each "root" galery, it become quickly unsable
* You can't look for a precise photo anymore without looking in every galleries

I don't know exactly how to solve this problem.
One way to help could be the have two management mode:
* auto-managed mode (ie: the current mode)
* self-managed mode, where you could select which directories to show as a gallery
Of course, you should be able to switch from one mode to another without loosing configuration.

Cheers,

P.S: current issue should be renamed with something clearer like "Custom galleries management"
