### ISSUE TITLE
AlbumsAdapter arraylist argument seems not changed by selected

### ISSUE THREAD

**Issue by chgmxx** [UnevenSoftware/LeafPic#356]
public AlbumsAdapter(ArrayList<Album> ph, Context context) ， the outside pass dispAlbums arraylist to ph, but the ph will not changed when dispAlbums changed. is that right? so, when select for album, the ui seems no change.

**Comment by chgmxx** [comment]
Sorry for my mistake. I found that in function 
public void swapDataSet(ArrayList<Album> asd) {
//compare the contents, not the object. so will return, albums will not  be updated
        //if (albums.equals(asd))
        //    return;

```
     //change to below:
     if (albums==asd)
        return;

    albums = asd;
    notifyDataSetChanged();
}
```

**Comment by dnldsht** [comment]
I have lookd into this, and sometimes it doesnt work (usaly when you change tje sorting order ASC/DESC) fixed in the dev branch
