### ISSUE TITLE
Crash when using external app video

### ISSUE THREAD

**Issue by ouafnico** [UnevenSoftware/LeafPic#363]
Hello

With the default option to use external video player, when trying to play a video make leafpic to crash (mxplayer).
Works if I enable internal player.

**Comment by dnldsht** [comment]
May I know wich android and app version are you using?

**Comment by ouafnico** [comment]
Of course. Android 7.0. The app is 0.5.9 (from fdroid)

**Comment by dnldsht** [comment]
upgrading to 0.6-beta-1 should fix this issue

**Comment by ouafnico** [comment]
I confirm the beta works for this. Thanks
