### ISSUE TITLE
Bug: long-pressing with a filter selects wrong items

### ISSUE THREAD

**Issue by marcelmindemann** [UnevenSoftware/LeafPic#366]
Hi, I am using Leafpic 0.5.9 on Android 6.0.1.
I have a folder with lots of saved content from reddit, this includes images, gifs and webms in a random order. There are about 2000 files in this folder, just mentioning this because I am not sure how related to the bug this is. To reproduce:
Navigate to a folder with images, gifs and videos
Set the view filter to only display one type of file, ie gifs only
Long press the first item to start selection mode. Item is selected with a tick and selection count is 1/2000
Now try to select some more items. Selection count will rise, but the items will not be selected
Even worse, when performing an action on the selection like deleting, the wrong files are deleted

**Comment by dnldsht** [comment]
fixed on the dev branch
