### ISSUE TITLE
[enhancement] getting Albums from Providers seems slow, can we minimize these calls ?

### ISSUE THREAD

**Issue by xtj-9182** [UnevenSoftware/LeafPic#367]
So I have lots of albums with a dozen on external storage as well.
When I browse albums and click on one and then go back,
`loadAlbums` from the `HandlingAlbums` class is ALWAYS called. So every time I go an Album and then I press back it will call `loadAlbums` every single time. This is slow on my device, I've tested it and the default MediaStoreProvider is the slowest, the Alternate MediaProvider is faster but still feels too slow for me. 

I was wondering if the calls to `loadAlbums` could either be minimized as in do it less often or only when really necessary, say when the `dispAlbums` ArrayList is empty. Ideally it would also be done when changes have occurred but I don't know if it's easy to detect that. Calling it every single time when going back from an Album seems too wasteful to me. 

edit: I'm currently testing a change on my fork where I simply change the loadAlbums method code to this:

  ``` java
public void loadAlbums(Context context, boolean hidden) {
    this.hidden = hidden;
    if (dispAlbums.isEmpty()) {
      ArrayList<Album> list = new ArrayList<Album>();
      if (SP.getBoolean(context.getString(org.horaapps.leafpic.R.string.preference_use_alternative_provider), false)) {
        StorageProvider p = new StorageProvider(context);
        list = p.getAlbums(context, hidden);
      } else {
        list.addAll(MediaStoreProvider.getAlbums(context, hidden));
      }
      dispAlbums = list;
      sortAlbums(context);
    }
  }
```

the added `if (dispAlbums.isEmpty())` makes it so that albums are only loaded when necessary of course this excludes the case of other changes happening to albums. ~~However the user could always do a manual update swipe in this case.~~

**Comment by dnldsht** [comment]
next release will handle this better

**Comment by xtj-9182** [comment]
ok thx
