### ISSUE TITLE
Swiping between pictures slow and jerky

### ISSUE THREAD

**Issue by CaviaPorcellus** [UnevenSoftware/LeafPic#368]
Swiping between pictures is now very jerky and a bit slow. In addition, often times when I swipe nothing happens, especially if an image just loaded. 

Yet swiping worked fine and was very quick in version .5.2. It became slow in .5.9; it remains an issue in .6-beta-1. 

Tested on a Nexus 5, Android 6.0.1.

**Comment by ghost** [comment]
I experience this as well. However for me it only happens on high-res photos taken with the camera app. It worsened in 0.6-beta-1 for me.

**Comment by aexvir** [comment]
I also experience this issue, Android 6.0.1, Leafpic 0.6-beta-1

**Comment by wyatt8740** [comment]
I can also confirm this on my Nexus 6 running Android 5.0.1.
The higher resolution the slower it is.

**Comment by ouafnico** [comment]
Same on 7.1.1 with last beta version
Menus very very slow, and crashing a lot

**Comment by oatberry** [comment]
Can confirm, Nexus 6P with CopperheadOS 7.1.1 and LeafPic v0.6-beta-1. Love this app, but resizing photos, swiping between photos, and using the overflow menu are all extremely laggy and slow.
