### ISSUE TITLE
Crash deleting screenshot

### ISSUE THREAD

**Issue by freefri** [UnevenSoftware/LeafPic#369]
LeafPic 0.5.9 crashes when deleting a screenshot on Nexus 4.
To reproduce:
1. Take a screenshot
2. Open the screenshot with LeafPic from the notification
3. Press the delete button in LeafPic
Then: LeafPic stops working
When I open LeafPic again the screenshot is in "displayed" but as a 404 image.

I could provide more info, just ask for it.

**Comment by dnldsht** [comment]
will dig into this, which version of android are you using? are screenshots on a sd card?

BTW there is the v0.6-beta-1 available.

**Comment by freefri** [comment]
I'm using the last official version of Android 5.1.1
The screenshot was located in /storage/emulated/0/Pictures/
The Nexus 4 does not have sd card, but it has a "storage" partition

I've upgraded to the LeafPic v0.6-beta-1 and I am not able to reproduce the problem anymore (I was expecting a beta to be less stable than a non beta) but the old 404 picture was still there. I've rebooted the phone and now it is gone.

**Comment by dnldsht** [comment]
@freefri it is related to #364 can you enable the alternative provider and give me the feedback?
