### ISSUE TITLE
Failed to resolve: uz.shift:colorpicker:0.5 

### ISSUE THREAD

**Issue by LoveqLRC** [UnevenSoftware/LeafPic#370]
`Error:(71, 13) Failed to resolve: uz.shift:colorpicker:0.5`  
Reported the wrong, how to solve?

**Comment by dnldsht** [comment]
according to `uz.shift:colorpicker`README you have just to include the repository:

```
repositories {
     maven {
        url  "http://dl.bintray.com/dasar/maven"
     }
}
```

and then the dependency:

`compile(group: 'uz.shift', name: 'colorpicker', version: '0.5', ext: 'aar')`

You should check if your ide has some trouble with the repository.
