### ISSUE TITLE
Pictures on SD Card are hiding after few seconds

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#371]
Whenever I open an image which sits in directory on SD card it shows for a second and then disappears. I only see a gray background..
Android 7.1, LeafPic 0.5.9.

**Comment by Jenna-66** [comment]
Did you try to activate "Sub-Scaling Image View" in the settings ?

**Comment by ghost** [comment]
Activating "Sub-Scaling Image View" helped. Now I can see my photos, thanks. Don't know if I should close this topic?
