### ISSUE TITLE
Clicking trash/delete button doesn't do anything

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#372]
When I want to delete image, open it and click trash button, nothing happens.
Android 7.1, LeafPic 0.5.9.

**Comment by Jenna-66** [comment]
I have the same issuee, when I try it the first time from the single-image view.
After doing the same from the album-view and allowing the access, it always works.

**Comment by dnldsht** [comment]
fixed with the last commit, added a progress dialog when you are deleting

**Comment by ghost** [comment]
Works out of the box now. Closing.
