### ISSUE TITLE
Tick on folder selection does not show up after theme change to Dark/AMOLED theme

### ISSUE THREAD

**Issue by williamchange** [UnevenSoftware/LeafPic#379]
**steps to reproduce**
1. Switch theme to Dark AMOLED/Dark theme
2. restart the app(swipe away from recents)
3. open the app again and try selecting any folder

It still shows how many folders i have selected in action bar but I cannot see which folder is selected ( no color/tick  highlight over folders), and switching back to white theme does not fix this.

**platform:**
Android 7.0, LeafPic v0.5.9, v0.6-beta-1
Android 6.0.1, LeafPic 0.5.9, v0.6-beta-1

**Comment by Valeria-AT** [comment]
No visual change here on Android 5.1.1, Leafpic 0.5.9 too. I always use dark theme.
