### ISSUE TITLE
Double-delete causes entire album to be deleted

### ISSUE THREAD

**Issue by apsun** [UnevenSoftware/LeafPic#386]
In the album view, when selecting multiple images and pressing the delete button twice in quick succession (before the first dialog appears), two confirmation dialogs are created. When clicking delete in the first dialog, it correctly deletes the selected images. However, clicking delete in the second dialog (which was behind the first dialog) causes the entire album to be deleted, which I think is unexpected behavior.

The relevant code is here: https://github.com/HoraApps/LeafPic/blob/3c8f8976aa2727df3488f09ef96b86386d1e8785/app/src/main/java/org/horaapps/leafpic/activities/MainActivity.java#L817

```
if (editMode)
  return getAlbum().deleteSelectedMedia(getApplicationContext());
else {
  boolean succ = getAlbums().deleteAlbum(getAlbum(), getApplicationContext());
  getAlbum().getMedia().clear();
  return succ;
}
```

After the first `DeletePhotos` task is executed, `displayAlbums()` is called in `onPostExecute()` which sets `editMode = false`. Then, when the second `DeletePhotos` task is executed, the `else` branch is taken which causes the entire album to be deleted.

I think a good solution would be to pass the selection as a parameter into the `AsyncTask`, so that the selection remains the same even if the instance state changes.

**Comment by dnldsht** [comment]
@apsun  thanks for the feedback will look into that.

**Comment by Sam-C-Dev** [comment]
I just had a whole folder get deleted during a move operation. I wonder if these are related....

https://github.com/HoraApps/LeafPic/issues/201#issuecomment-276457521

**Comment by dnldsht** [comment]
added a progress dialog on deleteting
