### ISSUE TITLE
map provider usage

### ISSUE THREAD

**Issue by wisemonkey** [UnevenSoftware/LeafPic#390]
This is not an issue, however I don't see how to use map provider.
And I was not sure where else to ask the question (no forum / wiki etc.)

**Comment by harshmittal2810** [comment]
When you click from the camera and you enable location on that, you will see your location of that image is clicked in Image property.

**Comment by wisemonkey** [comment]
Thanks 👍 I see it in file manager (Fx or on computer). LeafPic itself doesn't show it when I click on details, is that correct behavior?
