### ISSUE TITLE
album selection bug

### ISSUE THREAD

**Issue by kylm53** [UnevenSoftware/LeafPic#391]
when first time launch app,long click on album item,it's normal,but next launch or enter a album then back,long click to select an album, it can't show checked icon. 
So I modified the swapDataSet() method in AlbumsAdapter class:
``` 
public void swapDataSet(ArrayList<Album> asd) {
        if (albums == asd) //change "equals" to "=="
            return;
        albums = asd;
        notifyDataSetChanged();
 }
```

**Comment by Valeria-AT** [comment]
Does this also resolve https://github.com/HoraApps/LeafPic/issues/379 ?

**Comment by kylm53** [comment]
@Theobald93 Yes,I tried,it resoled #379
