### ISSUE TITLE
release schedule

### ISSUE THREAD

**Issue by alekksander** [UnevenSoftware/LeafPic#395]
hello!
when can we expect this excellent piece of software to be out of its beta stage? is there some kind of roadmap somewhere? i'd like to start recommending ;)
…or at least a new build going to be released soon?

thank You.

**Comment by sbobbo** [comment]
There hasn't been a real update in over 5 months. I'm pretty sure this has been abandoned.

**Comment by dnldsht** [comment]
@sbobbo the project isn't abandoned.

@alekksander no roadmap :)
I'm working on it, here are some things that I want to solve before a non-beta release

1. (In progress) rewrite the folder/media management with cool stuff to get performance increase 
2. (Need help) write from scratch an ImageView that allows zooming also on bigger images smoothly
3. (In progress) some new small features

I will release an update when the first in the list is completely done
If any developer out there knows and have time to do the second one, contact me or make a PR

If you want to stay updated check out the progress on the dev or on new branches but not on the master

**Comment by sbobbo** [comment]
Oh, that's very exciting to hear. Sorry about that.

**Comment by alekksander** [comment]
how is the progress on the issue?

**Comment by Cholker** [comment]
This is the best gallery I have used since the Non-Cheetah version of QuickPic. Though app is still fully functionable I hope there will be continuous support of this great gallery app. Thank you so much!

**Comment by dikiaap** [comment]
It's in alpha now. https://github.com/HoraApps/LeafPic/commit/7ca89a0d167d8b5418040281886045cf4583fe74

**Comment by dnldsht** [comment]
created a milestone and will continue to do that
