### ISSUE TITLE
ability to rotate images

### ISSUE THREAD

**Issue by Bugsbane** [UnevenSoftware/LeafPic#401]
Yes, I know that it says "coming soon" in the interface, but well... I'd really love to see this feature materialize. Half my images show up with the wrong rotation and it's really annoying that the feature to manually rotate them to the right way is always visible but not functioning.

Preferably, rotating would edit the exif information, so images stayed rotated every time they were looked at.

**Comment by mthor1234** [comment]
I'll take a crack at this

**Comment by Bugsbane** [comment]
Thank you, @mthor1234!
