### ISSUE TITLE
Opening an image from an intent doesn't load the image.

### ISSUE THREAD

**Issue by dkanada** [UnevenSoftware/LeafPic#403]
I have the same problem as #219 which was closed a while ago. LeafPic shows a blank screen when receiving an intent from any app on my phone as far as I can tell, namely Solid Explorer and Conversations. I have the latest version from F-Droid and am using a LineageOS nightly.

**Comment by iNPUTmice** [comment]
FWIW this is fixed in current dev. I can still reproduce this issue with the beta version from Google Play. Not sure which commit exactly fixed this and why.

**Comment by calvinnor** [comment]
Marking as fixed.
