### ISSUE TITLE
Crash when trying to "Edit with"

### ISSUE THREAD

**Issue by repsorp** [UnevenSoftware/LeafPic#408]
#11 05-23 08:10:19.036 W/System  (25758): ClassLoader referenced unknown path: /data/app/org.horaapps.leafpic-1/lib/arm64

Path should be:
/data/app/org.horaapps.leafpic-1/lib/oat/arm64

Config:
device: LGE bullhead | Nexus 5X | google | N2G47O
version: 7.1.2 | REL
LeafPic v0.6-beta-1

CrashLog:
[2017-05-23-08-11-17.txt](https://github.com/HoraApps/LeafPic/files/1021203/2017-05-23-08-11-17.txt)

**Comment by Ninnix** [comment]
up
