### ISSUE TITLE
resourse id not found

### ISSUE THREAD

**Issue by xiaming5368** [UnevenSoftware/LeafPic#411]
AlbumsAdapter.java
@BindView(R.id.linear_card_text) View footer;
@BindView(R.id.ll_n_media) View llCount;

id not found?

**Comment by jdbhanderi** [comment]
Error:(298, 23) error: cannot find symbol variable linear_card_text
Error:(299, 23) error: cannot find symbol variable ll_n_media
Error:(298, 47) error: Unable to parse @BindView binding.

please help!

**Comment by dnldsht** [comment]
fixed in dev branch
