### ISSUE TITLE
License fraud?

### ISSUE THREAD

**Issue by gsantner** [UnevenSoftware/LeafPic#415]
Hey there,
I found out about a lot of license violation recently of one of my GPLv3 apps.

I also found this one, maybe the project team is interested to hear about this:

* https://codecanyon.net/item/my-gallery/20324947?s_rank=17
* https://codecanyon.net/item/my-gallery/screenshots/20324947

Looks like LeafPic somewhat? ;)

@dnldsht  @Mow3l

**Comment by vxn2** [comment]
Fraud on my account pls help

**Comment by vxn2** [comment]
I havent signed in on my account in a week pls go through my gmail i almost died pls help

**Comment by vxn2** [comment]
I still havent found out how to transfer reasonable amounts to my paypal and bank account

**Comment by vxn2** [comment]
License violation and psychological trauma violation against my mental health and physical wellbeing

**Comment by gsantner** [comment]
That is not related to the app and to this issue..

**Comment by dnldsht** [comment]
I can't do nothing for other versions of leafpic! you had to download it via the links on the README or build it yourself!

Flag/Report other versions that looks malicius!

**Comment by gsantner** [comment]
both offers are down now.

**Comment by eMBee** [comment]
@gsantner did you do anything to have them taken down? other apps suffer the same fate, and i'd be interested to know if you know a way to get them removed from that site.

**Comment by gsantner** [comment]
I did contact the support and told them about the problem

**Comment by PaulWoitaschek** [comment]
Funny. For my project the same happened but they required me to write a formal "DCMA takedown notice".
