### ISSUE TITLE
Progress dialog when deleting media or albums

### ISSUE THREAD

**Issue by sbrl** [UnevenSoftware/LeafPic#433]
If I long press -> select a few items and then delete them, it just keeps 'loading' and doesn't actually delete anything.

If I press delete while viewing a single image, it hangs infinitely and I can't press either delete _or_ cancel.

Brand-new Nokia 5, all updates installed, running Android 7.

**Comment by smitsgit** [comment]
![activities-SplashScreen-09182017161252.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59bfa219c4a2d80013b8a78f/125516c66e82c728ace21e0d46e9978e2a948abd86ecac0e974dfc953a4e14703b01a6253dd5ba79e7102b50585e48ad435d5d56e0ebc969f9ec6923ce4e01ffd46a587cc66e44feecd31ee903e926834f85e7b58d18c1e12f39f5c9de116a415841c3aa1f27aa8b4ac052f74ee14852a712356ae277357c55d9.png)

**Comment by smitsgit** [comment]
Is this the kind of screen you see ? to better understand the hang behaviour , you are able to press cancel and use rest of the app but when you try to delete , this screen stays there forever.  Am i summerizing the issue in correct manner ?

**Comment by sbrl** [comment]
No, that's not the kind of screen I see. I see a spinning loader in a popup like that which hangs indefinitely. I can't back out or do anything else.

When try and delete an image from the big preview (by hitting the bin icon on the top bar), I get a confirmation dialog, but I can't select any of the options and the app then hands indefinitely.

**Comment by dnldsht** [comment]
@smitsgit I'm refactoring that dialog, soon you would see the progress and know if something fails

its already possible to cancel the operation on the dev branch

@sbrl where are stored the images?

**Comment by smitsgit** [comment]
@dnldsht Thanks for the info. The behaviour i see on the dev branch is , on the album list if i do long press and choose delete from the tool bar , the above pop up comes and stays there forever and when you finally cancel , the items are not deleted. I kinda figured out why that is happening. Let me know if i can chime in to help or file this as separate issue since you are already refactoring this part of code.

**Comment by sbrl** [comment]
@dnldsht Ah, awesome! So the next release should fix the issue? Cool. The images are stored in the default camera directory on the microSD card, though as far as I know the location of the images doesn't actually matter (the same happens in the downloads folder on the device, IIRC - though I'd need to double check).

**Comment by dnldsht** [comment]
> I kinda figured out why that is happening.

@smitsgit you can comment down below or file a new issue. Your choice!
