### ISSUE TITLE
Build error - dimensions

### ISSUE THREAD

**Issue by nico151999** [UnevenSoftware/LeafPic#439]
Dunno if it's just me or if it's a common error. Anyway, just wanted to check out the current state of development. I checked out the dev branch. A simple gradlew build wasn't successfull. Thus I tried it using Android Studio. Immediately I found out you're working with the 3.0 builds of Android Studio. Well, I downloaded it instantly and replaced my 2.3 version. However, even having this setup I get build errors telling me there are errors with the dimensions. Is this an error on my end or is it common? Thanks for your help in advance!

**Comment by roshani98** [comment]
Try resolving the error using Build>Clean project. Then sync your files.

**Comment by nico151999** [comment]
Thanks for the suggestion but I've already tried that

**Comment by dnldsht** [comment]
You should check of the version of gradle, sometimes Android Studio does not ask to update it. 
Or you can trying re importing the project. otherwise give me more info about the errors.
