### ISSUE TITLE
Fix icon color

### ISSUE THREAD

**Issue by dnldsht** [UnevenSoftware/LeafPic#443]
fix play video in selected icon color in AlbumsAdapter, MediaAdapter and MediaPagerAdapter

**Comment by thakkaryash94** [comment]
I would like to work on this.

**Comment by thakkaryash94** [comment]
So what I understand is we already set play icon to white but it is showing black in above adapters!

**Comment by dnldsht** [comment]
a pull request #447 is open for this issue

**Comment by thakkaryash94** [comment]
I just updated the library it is working, so may be I don't think those changes are required because then we are overriding xml icon color in java.
