### ISSUE TITLE
Hide folder not working!

### ISSUE THREAD

**Issue by tayyabahmad** [UnevenSoftware/LeafPic#454]
selecting the folder and marking it in OptionsMenu to hide doesn't do anything it just stays the same. Doesn't show up in "Hidden Folders" as well. Cant delete a folder from Hiden Folder. so please look at this issue. Btw good work app is good.

**Comment by tayyabahmad** [comment]
i was using the older version. the issue has been addressed in newer version. Thanks

**Comment by calvinnor** [comment]
@tayyabahmad @dnldsht This seems to be fixed in 0.6 beta 2.

Please verify and close the issue.
