### ISSUE TITLE
Feature request: Photo roll (sort by date, not folder)

### ISSUE THREAD

**Issue by Lesik** [UnevenSoftware/LeafPic#456]
Hey,

first of all, thanks to all contributors for this great app.

My favorite way to organize photos is to see them in a photo roll sorted by date, thrown together from several locations.

For example, with the following folder structure:
- `~/DCIM/Camera`
- `~/DCIM/BackupFromNikon`
- `~/Bluetooth`
- `~/Pictures/Screenshots`

I'd like Camera, BackupFromNikon and the pictures I received via Bluetooth to be shown in the photo roll, but not Screenshots (because those aren't photos). The list of folders to be in- or excluded is configurable by the user, of course.

Some examples of what I'm talking about:

![](https://i.imgur.com/jMBYMEU.jpg)
![](https://i.imgur.com/E52OCQq.jpg)

**Comment by dnldsht** [comment]
In the dev branch there are a feature that list all the media, would look
to add a feature that filter folders and maybe group them by some sort of
date range

**Comment by dnldsht** [comment]
#270
