### ISSUE TITLE
Folder Deleting not Working

### ISSUE THREAD

**Issue by harshmittal2810** [UnevenSoftware/LeafPic#458]
When I try to delete the folder, only alert dialog with the process is coming for a long time and image and folder not deleting.

**Comment by shashank1094** [comment]
It worked for me but the app crashed as soon as i press delete. I went back toh check if it was deleted or not and yes the folders were gone.

**Comment by harshmittal2810** [comment]
When I press delete now only dialog dismiss but folder not delete and That folder is in selected mode also.

**Comment by dnldsht** [comment]
#433
