### ISSUE TITLE
LeafPic Apps Bugs : Can Not Use Features "Edit With" (Crash)

### ISSUE THREAD

**Issue by dodybireuen** [UnevenSoftware/LeafPic#463]
Android is known as an open source operating system. Do not be surprised if many applications in source code free for many people. There are many reasons why developers make their apps open source, One of them is that the application can develop quickly because it is developed by the community.

![01.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510149630/yycrdigi1po2o7aypjqb.jpg)

LeafPic is one of many open source applications, LeafPic is a photo gallery app based on android.  This application is like a gallery application in general that has the ability to display photos and videos on Android OS smartphones. 

![2017_11_08_20_47_13_20_47_53.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510149658/ysi8xs6rd1b6r1p95dl0.gif)

One of the interesting features of the LeafPic is able to display the detail information of a photo including the camera settings in use. In addition LeafPic also gives protection feature so that the photos in the Gallery could not be accessed by anyone. LeafPic applications can be downloaded via Google Play Store.

However I still find 1 bugs when using LeafPic app, this bugs should soon be fixed in the next  LeafPic release :
***
***
***
#### Features Edit With
Photo in LeafPic app can not be edited using other application although the edit menu with already provided. When the edit with feature is in use then LeafPic app will be closed (crash) with notification "LeafPic has stopped, open the app again". This condition is very difficult when users want to do photo editing using other applications.

![2017_11_08_20_50_28_20_51_16.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510149720/ufetr0dq1nyursx8fpxy.gif)
***
***
***
##### Devices in use
| NO |      Device     |        OS        |           App          |
|:--:|:---------------:|:----------------:|:----------------------:|
|  1 | Samsung S7 EDGE | Android - Nougat | LeafPic Gallery [BETA] |

***
***
***
##### Bug LeafPic in the table form
| NO |        Bugs       |     Notification    |
|:--:|:-----------------:|:-------------------:|
|  1 | Feature Edit With | LeafPic has stopped |

Hopefully the bugs that still appear in the LeafPic app can be resolved, so that it can improve the comfort and satisfaction of users.

@dodybireuen
<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@dodybireuen/leafpic-apps-bugs-can-not-use-features-edit-with-crash">Utopian.io</a></em><hr/>

**Comment by dnldsht** [comment]
fixed in the dev branch, can you sum me up what utopian.io does?

**Comment by dodybireuen** [comment]
utopian.io is an open source community. You can check this [link](https://steemit.com/@utopian-io) , there are many developers and open source lovers there. They compete to contribute to open source applications. I think Utopian.io is a great open source community
