### ISSUE TITLE
Error:Unable to resolve dependency for ':app@withGPlayDebugUnitTest/compileClasspath': Could not resolve uz.shift:colorpicker:0.5.

### ISSUE THREAD

**Issue by bdzypcy** [UnevenSoftware/LeafPic#467]
Error:Unable to resolve dependency for ':app@withGPlayDebugUnitTest/compileClasspath': Could not resolve uz.shift:colorpicker:0.5.

**Comment by dnldsht** [comment]
unfortunately this project has no UnitTest
