### ISSUE TITLE
App crashes when trying to share image on Oreo

### ISSUE THREAD

**Issue by matejdro** [UnevenSoftware/LeafPic#470]
Running `v0.6-beta-1` from play store. Every time I try to share an image, it crashes with [FileUriExposedException](https://developer.android.com/reference/android/os/FileUriExposedException.html).

**Comment by iNPUTmice** [comment]
I just tried LeafPic for the first time and ran into the same issue. Looking through the code I think this has been fixed in 024374baec3268f88c439ba2fc8a4fc42d086a78.

edit: Can confirm that dev branch does indeed fix the issue.

**Comment by matejdro** [comment]
Wow that was quite a long time ago. Any chance we can get updated apk?

**Comment by Truffel71** [comment]
Just wanted to report that the issue still exist.
I recently discovered this app and without this bug it will be great!!
