### ISSUE TITLE
Missing icons? 

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#471]
Just a couple of hours ago I compiled the apk from source and the icons don't appear in the sidebar not the settings menu. I compiled a debug version ( noGPlay) first and everything worked perfect but when I compiled the release version and there found this issue. I compiled all 4 versions ( Debug GPlay, Debug NoGPlay, Release GPlay, Release NoGPlay) and I found this issue only in the release candidates. The debug version runs perfectly. Am I missing something or is it a bug?

**Comment by dnldsht** [comment]
can you rebuild with the last commit? are they just missing or they have the wrong color?

**Comment by ghost** [comment]
Rebuilt with last commit as suggested. Issue still persists. They are missing, can confirm. Because even after changing theme, they still do not show up. 

P.S: I'm no developer. I compiled the app from source because the released apk was outdated. But I haven't touched a single file so I doubt if there's any problem from my end.

**Comment by dnldsht** [comment]
Are they all missing? Which android version are you using? Can you check if
the log give some useful info?

**Comment by ghost** [comment]
I have attached a log of error I get when I open the app and even the screenshots with all three themes to help you understand the problem better. Seems like some naming issue. I am running android version 7.1.2.

[adb.txt](https://github.com/HoraApps/LeafPic/files/1530047/adb.txt)

[screenshot_20171205-122746](https://user-images.githubusercontent.com/33492285/33594983-2f396cc4-d9bc-11e7-84cc-7ab8121fa277.png)
[screenshot_20171205-122755](https://user-images.githubusercontent.com/33492285/33594984-2f9ce6f0-d9bc-11e7-818e-1943d56c1c04.png)
[screenshot_20171205-122803](https://user-images.githubusercontent.com/33492285/33594985-2fd6a304-d9bc-11e7-8823-d1b4f5a06991.png)
[screenshot_20171205-122807](https://user-images.githubusercontent.com/33492285/33594986-30141da6-d9bc-11e7-8929-fc43a0d09fd0.png)
[screenshot_20171205-122812](https://user-images.githubusercontent.com/33492285/33594987-304f3cb0-d9bc-11e7-9d67-694fe230f74d.png)
[screenshot_20171205-122820](https://user-images.githubusercontent.com/33492285/33594988-3089b1d8-d9bc-11e7-8dea-8f49517fb81f.png)

**Comment by dnldsht** [comment]
can you build the last commit?

**Comment by ghost** [comment]
No change.
adb logcat gives error : E Iconics : Wrong icon name: gmd_gif
plus multiple different names all starting with gmd_

**Comment by calvinnor** [comment]
@theblahblahmachine @dnldsht This issue seems to be fixed in 0.6 beta 2.

Could you verify and close the issue?

**Comment by ghost** [comment]
I have compiled v0.7-alpha1, 15 and can confirm that the issue has been fixed. Thank you for your support. I'm closing the issue.
