### ISSUE TITLE
Update ExoPlayer

### ISSUE THREAD

**Issue by dnldsht** [UnevenSoftware/LeafPic#472]
update [exo-player](https://github.com/google/ExoPlayer)  to 2.60 and solve change breaks

**Comment by AmrishJhaveri** [comment]
Hey, I would like to take up this open issue. Do you have any wiki of the process you follow for the project? Also by change breaks you mean line ending issues? Can you provide some more details?

**Comment by dnldsht** [comment]
There is already a pull requests going on https://github.com/HoraApps/LeafPic/pull/483
