### ISSUE TITLE
Large delays when deleting images

### ISSUE THREAD

**Issue by Bugsbane** [UnevenSoftware/LeafPic#477]
Whenever I delete images, it takes around 10 seconds or more *per image* to delete it, so if I try to delete say 30 images, the app locks up for around 5 minutes.

This is after giving the app permission to read/write my storage card. The stock gallery app, deletes the same 30 images off of the storage card in about 2 seconds.

I'm wondering if this may be related to issue #241, especially seeing as delays seem larger in folders with more images (the folder used here had 1400 images)

Android 6.0.1
LeafPic 0.6 Beta 1 from Fdroid

**Comment by dnldsht** [comment]
made it async also shown progress #558
