### ISSUE TITLE
Error Importing Packages 

### ISSUE THREAD

**Issue by iambaji** [UnevenSoftware/LeafPic#481]
![capture](https://user-images.githubusercontent.com/20913054/34082382-22ebce14-e383-11e7-820c-8b7565d08189.PNG)
Sorry if this is newbie question, i already serched the web but didn't find any solution. i just started with github and imported this project but i am getting the error "can'nt resolve" , problem with importing packages. can anyone tell me what i am doing wrong?

I already tried restarting the studio
Invalidate Cache/Restart 
Clean Build

**Comment by dnldsht** [comment]
Which version of AS are you using? have you tried Synch or Clean the project?

**Comment by iambaji** [comment]
I am using latest version android 3.0.1, by Sync and Clean if you mean Ivalidate Cache/Restart,Clean Build Project,Rebuild Project, yes i did that

**Comment by dnldsht** [comment]
you must try to re-import the project also check if you set the last version for gradle plugin

**Comment by iambaji** [comment]
Solved
If i am not wrong, the AS 3.0.1 is creating  a ".idea" folder as a parent directory of all projects. earlier when was cloning the leafpic from github i haven't changed the parent directory path (one with .idea) 
Now i again imported the leafpic but gave a different parent directory, and it is working fine. so i guess the problem is with the parent directory path. anyway, thank you 👍  @dnldsht 

can i delete the issue? i feel a bit embarrassed posting basic IDE problems on project issues :p
