### ISSUE TITLE
what is this methode : setScrollViewColor ??

### ISSUE THREAD

**Issue by ridaeh** [UnevenSoftware/LeafPic#485]
Could you explain to me what this methode do ?? I didn't find anything about it ... thanks in advance 
https://github.com/HoraApps/LeafPic/blob/7ca89a0d167d8b5418040281886045cf4583fe74/app/src/main/java/org/horaapps/leafpic/activities/SettingsActivity.java#L97

**Comment by dnldsht** [comment]
You can check it here
https://github.com/HoraApps/Liz/blob/master/library/src/main/java/org/horaapps/liz/ThemedActivity.java
