### ISSUE TITLE
Can't Play Videos and searchbar not working 

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [UnevenSoftware/LeafPic#487]
1.  i am trying to play video with MX-player but showing error can't play this but after enable from setting "Include internal Vidio Player" it  worked well pls check and the other thing i found is 
2. Search Bar is not working

3. I can't found Gif easily

**Comment by dnldsht** [comment]
1) is done
3) you can filter images by type

2) this has a very low priority
