### ISSUE TITLE
debug:orientation' not found.

### ISSUE THREAD

**Issue by mohamedkhairy953** [UnevenSoftware/LeafPic#488]
Error:error: attribute 'org.horaapps.leafpic.debug:orientation' not found.

this error has appeared while building project in two file 

LeafPic\app\src\main\res\layout\dialog_color_picker.xml

LeafPic\app\src\main\res\layout\dialog_media_viewer_theme.xml

**Comment by calvinnor** [comment]
@mohamedkhairy953 Could you describe your issue further?

Are you having trouble in building LeafPic? Which git branch are you building?
Please provide more information so that we can assist you.
