### ISSUE TITLE
App stops working after re-opening

### ISSUE THREAD

**Issue by ThePuff** [UnevenSoftware/LeafPic#493]
When i press the home button, and come back to the app after a while, app stops working.

Sony Xperia Z3
Android 6.0.1
Not Rooted

**Comment by calvinnor** [comment]
@ThePuff Hello :)

We've fixed a bucketload of crashes and bugs recently, we'd like you to try out the latest version of LeafPic and let us know if we've fixed the issue for you.

You can either
1. Clone the repo and make a build
2. Wait, and we will alert you when we're ready for a new release

Thank you for reporting this issue and using LeafPic!
