### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#494]
I am seeing no updates piblished since 10/10/2016, is this project still in development?

**Comment by calvinnor** [comment]
@xxvixxy Hello, thank you for using LeafPic!

Yes, the project is still in development. You can check out some recent commits and WIP branches.

We're planning on establishing a release cycle for regular builds. We'll let you know when we do :smile:

Feel free to look around, suggest features, file bugs or anything that can help us make the application better :sunglasses:

**Comment by ghost** [comment]
I installed, and will post any bugs if any come through. Take your time, and have fun! :)
