### ISSUE TITLE
Translating

### ISSUE THREAD

**Issue by StanioHrutc** [UnevenSoftware/LeafPic#498]
Problem with translating all elements of list in menu -> parameters, only part of items are translating on ukrainian

**Comment by StanioHrutc** [comment]
Hi guys, just catched this issue,  i haven't a lot of experience in open-source projects, how i can fix it?
![Screenshot_2018-01-19-21-00-21-622_org.horaapps.leafpic.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a61d5daaaed3200135a8af0/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416763e785dee7921c8b378f2102a4c595d4cc31e1a085aa4a6cb7af7f67c3394005ebc872d0627d42103ecfadd45ea52fe32815d80b1bb824c93bd6f71b68ad94d6d180d1889ae5432f49842da44e409b01301fb4e6f29b334247655961f7f2d6e6620a8f4d654828461a1b20262.png)

**Comment by dnldsht** [comment]
you can translate them on [crowdin](https://crowdin.com/project/leafpic) give me your username after you sign-up I can set you as a translator!
