### ISSUE TITLE
Security password does not lock the application. 

### ISSUE THREAD

**Issue by umair1209** [UnevenSoftware/LeafPic#501]
#### Expected behavior
When you set up a security password on an application, it will ask you to enter the password if you try to open it. 

#### Actual behavior
When I tried to set up a security password to secure my data, it did turn on the security but when I closed the app and opened it again, it never asked me to enter a password. 
I did this multiple times and got the same result. 

#### How to reproduce
- Open LeafPic 
- Click on menu and open security settings
- Set up a password and close the application 
- Open the application again and it will never ask you to enter a password. 

* Browser: Google Chrome for Android 63.0.3239.111
* Operating system: Android 6.0.1

#### Recording Of The Bug

 https://youtu.be/CXFDv24cNPc

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedumair/security-password-does-not-lock-the-application">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dnldsht** [comment]
Actually that's the desired behavior it ask for the password only if you
try to open hidden folders, or delete something if you have set up them in
the settings
