### ISSUE TITLE
App crashes while sharing a video 

### ISSUE THREAD

**Issue by umair1209** [UnevenSoftware/LeafPic#503]
#### Expected behavior
When you click on share video, we should be able to share videos on desired platforms. 
#### Actual behavior
When you click on share a video option, the application crashes

#### How to reproduce
- Open a video 
- Click on share option and the application will crash. 

* Browser: Google Chrome for Android 63.0.3239.111
* Operating system:  Android 6.0.1

#### Recording Of The Bug
![20180129_165016.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517231516/errcmstovs0trm2k0m5a.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedumair/app-crashes-while-sharing-a-video">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by carusooo** [comment]
This appears to be fixed at HEAD (v0.7-alpha), I was able to repro using the Play Store version (v0.6-beta-1). Which version of LeafPic are you using?

**Comment by dnldsht** [comment]
Closing as dup and fixed in dev
