### ISSUE TITLE
Force use of accelerometer does not work

### ISSUE THREAD

**Issue by umair1209** [UnevenSoftware/LeafPic#506]
#### Expected behavior
The LeafPic application has a feature through which you play videos in landscape mode even if your auto rotate feature is disabled. 
Every application which has this feature enables users to view videos in landscape mode. 
#### Actual behavior
When you turn the force use of accelerometer feature on, it does not work, that is you are not able to watch videos in landscape mode. 
#### How to reproduce
- Turn on force use of accelerometer feature 
- Open a video in Leafpic 
-  Rotate your phone and you will see that the landscape mode is not enabled. 

* Browser: Google Chrome for Android 63.0.3239.111
* Operating system: Android 6.0.1

#### Recording Of The Bug

https://youtu.be/A5S64ku1NwQ

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedumair/force-use-of-accelerometer-does-not-work">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dnldsht** [comment]
Actually that's the right behaviour, force accelerometer works when you are seeing pictures in full screen (the view before you click play), in the video player there is a button on the toolbar that toggle the orientation that is more convenient
