### ISSUE TITLE
My permission...

### ISSUE THREAD

**Issue by raja-rizki** [UnevenSoftware/LeafPic#512]
Greetings, LeafPic team.

I would like to volunteer to be a moderator of Indonesian translation on this project, if you wish and allow me to advise, I will advise that:
1. very good if the translation in crowdin is launched to github. because many I found some members of the translator on the project crowdin tried to translate to github, not just on this project, many also happened to other projects.

hopefully I am accepted and can help.
best regards: raja rizki
my github: https://github.com/raja-rizki

**Comment by dnldsht** [comment]
you can approve the translation for Indonesian on crowdin, it 70% translated, hope you can moderate them well.
Thank you for the collaboration!
I will update then the strings on GitHub.

**Comment by raja-rizki** [comment]
thanks you :+1:
