### ISSUE TITLE
Drag for selection

### ISSUE THREAD

**Issue by akorb** [UnevenSoftware/LeafPic#517]
Just like in Google Photos.

Example: https://www.androidpolice.com/wp-content/uploads/2015/06/nexus2cee_qp.gif

Hold the preview image of a photo until it is selected and then start shifting across other images. They should be selected too. Just like using the Shift key on a desktop PC.

https://github.com/afollestad/drag-select-recyclerview might be helpful

**Comment by aaronallenCS** [comment]
I would close this issue as this functionality has already been implemented.
