### ISSUE TITLE
Design Help

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#521]
Are you guys looking to redesign or improve current design?

I'm a UI/UX designer and would love to contribute. If you can point me to any other projects that is in need to UI/UX help, let me know.

**Comment by dnldsht** [comment]
Not a complete redesign but some improvements, if you have an idea, please share!

I would love to redesign the video player to improve the UX and keeping a good UI

**Comment by calvinnor** [comment]
Hello @Yasha08, thanks for using LeafPic!

We would like to see your thoughts / designs.
Obviously, slight modifications here and there are a good way to start.

But feel free to let us know if you have some great ideas, we'd love your help :+1:
