### ISSUE TITLE
how can Construct MediaStore URI for specific folder search

### ISSUE THREAD

**Issue by miladr0** [UnevenSoftware/LeafPic#524]

**Comment by miladr0** [comment]
i just want to show "example folder" as root of my gallery not whole sd card media
`
Query.Builder query = new Query.Builder()
                .uri(MediaStore.Files.getContentUri("external"))
                .projection(Album.getProjection())
                .sort(sortingMode.getAlbumsColumn())
                .ascending(sortingOrder.isAscending());

        ArrayList<Object> args = new ArrayList<>();

        if (Prefs.showVideos()) {
            query.selection(String.format("%s=? or %s=?) group by (%s) %s ",
                    MediaStore.Files.FileColumns.MEDIA_TYPE,
                    MediaStore.Files.FileColumns.MEDIA_TYPE,
                    MediaStore.Files.FileColumns.PARENT,
                    getHavingCluause(excludedAlbums.size())));
            args.add(MediaStore.Files.FileColumns.MEDIA_TYPE_IMAGE);
            args.add(MediaStore.Files.FileColumns.MEDIA_TYPE_VIDEO);

        } else {
            query.selection(String.format("%s=?) group by (%s) %s ",
                    MediaStore.Files.FileColumns.MEDIA_TYPE,
                    MediaStore.Files.FileColumns.PARENT,
                    getHavingCluause(excludedAlbums.size())));
           args.add(MediaStore.Files.FileColumns.MEDIA_TYPE_IMAGE);

        }

        //NOTE: LIKE params for query
        for (String s : excludedAlbums)
            args.add(s+"%");

        query.args(args.toArray());

        return QueryUtils.query(query.build(), context.getContentResolver(), Album::new);`

**Comment by dnldsht** [comment]
If I understood well it should look like this:
```
Query.Builder query = new Query.Builder()
.uri(MediaStore.Files.getContentUri("external"))
.projection(Album.getProjection())
.selection(String.format("%s LIKE ?", MediaStore.Files.FileColumns.DATA))
.args(String.format("%/%s/%", "folder_name"))
```

so the query will be like `SELECT ... FROM ... WHERE _data LIKE %/folder_name/%`
