### ISSUE TITLE
App crashes when we try to rotate gifs

### ISSUE THREAD

**Issue by umair1209** [UnevenSoftware/LeafPic#526]
#### Expected behavior
The application should rotate the gif as we command it or should just say this feature is not available yet if it isn't released. 

#### Actual behavior
I tried rotating the gif file and suddenly the application crashed. 
This bug works on gif only and although the feature is unreleased but that should not lead to the crashing of app. 

#### How to reproduce
- Open LeafPic 
- Select a gif file and try to rotate it
- Clicking on rotate will follow the crashing of the application. 

* Gallery : LeafPic latest version 
* Operating system: Android 6.0.1

#### Recording Of The Bug

https://youtu.be/7tS_7RPcOCM
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedumair/app-crashes-when-we-try-to-rotate-gifs">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by calvinnor** [comment]
@umair1209 Thanks for reporting this issue!

It is reproducible with any GIFs, we are actively working to fix it! :)

**Comment by calvinnor** [comment]
Fixed in #528
