### ISSUE TITLE
Bug in LeafPic App: delete photo not working

### ISSUE THREAD

**Issue by rudiansyah1996** [UnevenSoftware/LeafPic#531]
#### Expected behavior
I want to delete the photo via LeafPic application, but when I delete it poto is not also deleted, many times I delete it is also not deleted, which should after pressing delete button automatically deleted by itself poto.

#### Actual behavior
delete photo in leafPic application does not work. when I want to delete poto delete button does not work, I have repeatedly pressed delete also not deleted the photo.

#### How to reproduce

*  Browser: **LeafPic Gallery [Beta] Version (v0.6-beta-1)**
*    Operating system: **Android 5.0**
* Smartphone: **Asus Zenfone 4s**

#### Recording Of The Bug
https://youtu.be/eB9stD8FTyw

**Comment by TakuCoder** [comment]
is the file is still available in the storage? or it deleted and failed to refresh the view?

**Comment by Hubcapp** [comment]
Still available in storage. It's on the SD card, app has all the permissions it's asked for.

**Comment by HowlingMind** [comment]
I believe this has to do with SD Card permissions. Delete worked for me off of internal storage, but when I moved the pics to my SD Card, I was getting this same behavior.

**Comment by Hubcapp** [comment]
I opened a root terminal on my phone and "chmod -R 777" to the folder, but it still didn't work. Frustrating.

I am able to use Amaze file manager to delete files on SD card, so it is an application error, not permissions.

**Comment by calvinnor** [comment]
It seems (from your discussion) that you can't delete media when it's on the SD Card.

I'll have a look at this when I get the time. 
Thanks guys for your findings and reports!
