### ISSUE TITLE
Zoom feature is not working after cropping image in LeafPic. 

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [UnevenSoftware/LeafPic#534]
#### Expected behavior
After cropping image, want to zoom it by dragging two fingers or by double tapping on image. It must be able to zoom the cropped image. 

#### Actual behavior
After cropping image, when i tried to zoom it, it is not working. 

#### How to reproduce
Install app from f droid. 

Open it. 

Open any folder.

Crop the image through its edit feature.

Save it. 

Then zoom upon cropped image. 

It is not working. 

* Browser: LeafPic[Beta]
* Version:0.6-Beta-1
* Operating system:5.1.1

#### Recording Of The Bug
https://youtu.be/342Vh8ff1oM
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/zoom-feature-is-not-working-after-cropping-image-in-leafpic">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by calvinnor** [comment]
@PeerzadaZeeshan Hello, thank you for reporting this bug!

It is reproducible on the latest version, as per your steps to reproduce.

However, it could be due to the image being small enough to disable zooming.

@dnldsht Could you confirm if this is the expected behaviour?

**Comment by dnldsht** [comment]
yeah the cropped image is just too small
