### ISSUE TITLE
Rate app option is not functional 

### ISSUE THREAD

**Issue by umair1209** [UnevenSoftware/LeafPic#539]
#### Expected behavior
Clicking on rate app option should take us to the play store and let us rate the application. 

#### Actual behavior
When I clicked on the rate app option, it didn't take me to play store. 
Clicking on rate option won't take you anywhere. 

#### How to reproduce
- Open leafpic 
- Click on about 
- Click rate and you will see the option is not functional. 

* Application: LeafPic v 0.6-beta-1
* Operating system: Android 6.0.1

#### Recording Of The Bug

https://youtu.be/7V2Ms2bIhM4    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedumair/rate-app-option-is-not-functional">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by aaronallenCS** [comment]
I have since fixed this issue... closing the issue i would think is necessary
