### ISSUE TITLE
Enable, Disable internal video player option fastly crashes the app

### ISSUE THREAD

**Issue by the-codingninja** [UnevenSoftware/LeafPic#541]
<div class="Body Body--full"><div><h4>Expected behavior</h4>
<p><strong>Internal video player</strong> option should work when enable and work according to it. And stopped working when we disable it or repeat the same steps any no. of times.</p>
<h4>Actual behavior</h4>
<p>When we enable the <strong>Internal video olayer option</strong> and then disable it and repeat this process will crash the app and app stopped working.</p>
<h4>How to reproduce</h4>
<ul>
<li>Open the settings menu of <strong>Leafpic</strong> and enable the <strong>Internal Video Player</strong> option as shown in this Screenshot.
<img src="https://cdn.utopian.io/posts/14ab73a6f829cabd954b1b83ff58a2a3e5cbIMG-20180408-WA0018.jpg" alt="IMG-20180408-WA0018.jpg"></li>
<li>Now disable this option and repeat same  process atleast 3 times with no break in time.</li>
</ul>
<ul>
<li>Leafpic: Version 0.6-beta-1</li>
<li>Operating system: Android Nougat 7.0</li>
</ul>
<h4>Recording Of The Bug</h4>
<p></p></div><div>

 Recording of the bug can be found here - https://www.youtube.com/embed/jYdlB8R27vY?autoplay=1
</div><div><p></p>
<p><br></p><hr><em>Posted on <a href="https://utopian.io/utopian-io/@faisalamin/enable-disable-internal-video-player-option-and-repeat-this-process-3-times-fastly-crash-the-app" target="_blank" rel="nofollow noopener">Utopian.io -  Rewarding Open Source Contributors</a></em><hr><p></p></div></div>

**Comment by the-codingninja** [comment]
This issue was reported by @rockstar96969696

And I found a similar issue closed here - 

https://github.com/HoraApps/LeafPic/issues/405

**Comment by calvinnor** [comment]
@ms10398 Hi Mohit!

This option has been removed as of 0.7 (unreleased), probably why #405 was closed without comment.
It has been replaced with a lot of rework and a better video player.
Will update you on this when we're ready for release, so that you can verify if we fixed your issue.

Thanks!

**Comment by the-codingninja** [comment]
Thanks @CalvinNor :slightly_smiling_face:
