### ISSUE TITLE
i am korean,  I want to translate the contents of string.xml into Korean.

### ISSUE THREAD

**Issue by KooYS** [UnevenSoftware/LeafPic#574]
I am a user of this app. 
I want to translate string.xml to Korean for Korean.

Can I translate without the use of Crowdin?

**Comment by calvinnor** [comment]
@KooYS Hey, welcome to LeafPic :)

Thanks for putting forth your contribution idea, but I'm not familiar with translations.

@dnldsht would help you, sorry for the late reply! :blush:
