### ISSUE TITLE
Rate Button not working in About page

### ISSUE THREAD

**Issue by horpeyloaded** [UnevenSoftware/LeafPic#583]
#### Expected behavior
When the *Rate button* is clicked, it should open the The app rating on playsore so users can rate the App.

#### Actual behavior
When the rate button is clicked it does nothing

#### How to reproduce
  - Open the App
  - Click the Menu button on the top left
  - Select about
  - Stroll down to support development 
  - click the **Rate button** from the list 
***
* App version: LeafPic v0.6
* Operating system: Android 6.0, Marshmallow
* Device: Tecno C9 Pro

**Comment by Temidtech** [comment]
@horpeyloaded i have fixed this issue.
