### ISSUE TITLE
Factors Behind Updating Third-Party Libraries in Mobile Apps

### ISSUE THREAD

**Issue by arakhia** [UnevenSoftware/LeafPic#618]
Hello LeafPic developers,

I'm a master student studying third-party libraries update behavior, and trying to build a tool that can help app developers with 3rd party libraries update. The tool should provides insights to developers about libraries in their apps, hence, developers can make better decisions when updating those libraries. The following survey study factors that motivate the update decision.

Please participate in our survey it should only take 4~8 minutes. Your contribution is very important, the answers are anonymously collected.

Survey Link
https://forms.office.com/r/mNp2tcYe7D

Thank you for your time and feedback

**Comment by arakhia** [comment]
Please consider participating in my survey.
@dnldsht @gilnd @calvinnor @rupak0577 @lorisgir @Sysmain @tonyzzp @tauquir @brandonio21 @macarus0 @dethstar @LDongGyu @TrebuhD @abhimaniCodal @Arjun-sna @licaon-kter @adam-poteralowicz @akm0012 @KignorChan @51114u9 @pylerSM @pelya @smeyyeac @Grandolf49 @d4rken @thakkaryash94 @aaronallenCS @tahirmoedeen53

**Comment by licaon-kter** [comment]
@arakhia can you stop spamming all the projects pls?

**Comment by g1lg1l** [comment]
@arakhia why is this an issue ? this is unrelated topic, also this project is no longer maintained!

**Comment by arakhia** [comment]
@gilnd 
Sorry for any inconvenience, I will not mention you anymore. I just opened the issue as I found it the only way to reach to you guys, I didn't find discussion forums in your project, and I need to find app developers who are willing to answer the survey.

Thanks for your time.
