### ISSUE TITLE
Getting this into F-Droid

### ISSUE THREAD

**Issue by tian2992** [UnevenSoftware/LeafPic#86]
Hello!
seems like a pretty cool app, I'd love to see it on fdroid

cheers!

**Comment by dnldsht** [comment]
LeafPic will be available on the Play Store and on F-Droid soon, we have to improve it before the release.

cheers!

**Comment by pizzamaker** [comment]
Relevant thread at F-Droid: https://f-droid.org/forums/topic/leafpic-foss-gallery/

**Comment by ghost** [comment]
I added a build but added a `-dev` suffix. @DNLDsht, should I cancel the build for F-Droid or is it okay to publish the current snapshot?

**Comment by polyzen** [comment]
This apparently can be closed ^^
