### ISSUE TITLE
Fix lint translation warnings

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#88]
I have to add `"android { lintOptions { disable 'MissingTranslation' } }"` to ignore translation warnings, however disabling/enabling this should be handled by upstream, since you know best when this is needed and when not.

**Comment by dnldsht** [comment]
added in the last [commit](https://github.com/DNLDsht/LeafPic/commit/4b650ab25414c7c3e8b5f99ad610a78fee3551e6)

**Comment by ghost** [comment]
You want also to add `disable 'ExtraTranslation'`.

**Comment by dnldsht** [comment]
@krt16s  just added but i never get any error durind compling
