### ISSUE TITLE
Feature - Hide and unhide hidden folders

### ISSUE THREAD

**Issue by rouke-broersma** [UnevenSoftware/LeafPic#99]
I would like to have the ability to hide and unhide hidden folders from the hamburger menu, and have a passcode lock on unhiding.

**Comment by g1lg1l** [comment]
We will talk about it, and as soon as  we can we will do it, stay tuned. :)

**Comment by zkvvoob** [comment]
Hi there!

I was just about to write here and say how much I like LeafPic and that the only thing missing for me was that precise ability to hide/show hidden folders, when I saw this post. 

So, I second that request. :)

Keep up the good work!
